import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.cybersecurity': 'Cybersecurity',
    'nav.iot': 'IoT Solutions',
    'nav.software': 'Software Solutions',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.regulations': 'Tunisian Regulations',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'Providing robust cybersecurity and innovative IoT solutions to secure your digital future.',
    'footer.quickLinks': 'Quick Links',
    'footer.ourServices': 'Our Services',
    'footer.getInTouch': 'Get in Touch',
    'footer.phone': 'Phone',
    'footer.address': 'Address',
    'footer.location': 'Megrine, Ben Arous',
    'footer.country': 'Tunisia',
    'footer.contactUs': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    
    // Home
    'home.hero.title': 'Strong Security for an Interconnected World',
    'home.hero.description': 'Protecting your business with advanced cybersecurity and intelligent IOT solutions',
    'home.hero.cta': 'Contact Us',
    'home.services.title': 'Our Core Services',
    'home.services.cyber.title': 'Cybersecurity Services',
    'home.services.cyber.desc': 'Proactive defense against evolving digital threats',
    'home.services.iot.title': 'IoT Services',
    'home.services.iot.desc': 'Secure and seamless integration of smart devices',
    'home.services.managed.title': 'Managed Security & Support',
    'home.services.managed.desc': '24/7 monitoring, rapid response, and expert guidance',
    'home.testimonials.title': 'What clients say',
    'home.testimonials.1': '"IRONHEX secured our IoT rollout and improved monitoring — their team is top notch."',
    'home.testimonials.1.author': '- CTO, Acme Corp',
    'home.testimonials.2': '"Response times and the expertise are exceptional. Recommended."',
    'home.testimonials.2.author': '- Head of IT, Beta Ltd',
    'home.partners.title': 'Our partners',
    
    // Contact Form
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    
    // Software Solutions
    'software.title': 'Ready-Made Website Solutions',
    'software.subtitle': 'Professional, fully-functional website platforms ready to deploy. Request a live demo to see them in action.',
    'software.features': 'Key Features:',
    'software.technologies': 'Technologies:',
    'software.requestDemo': 'Request Live Demo',
    'software.customTitle': 'Need a Custom Website Solution?',
    'software.customDesc': 'Our team can develop a tailored website platform specifically designed for your unique business requirements',
    'software.customCta': 'Contact Us for Custom Development',
    
    // Demo Request
    'demo.title': 'Request Demo',
    'demo.description': 'Fill in your details and we\'ll schedule a personalized demo session to showcase the platform\'s capabilities.',
    'demo.fullName': 'Full Name',
    'demo.email': 'Email Address',
    'demo.phone': 'Phone Number',
    'demo.company': 'Company Name (Optional)',
    'demo.message': 'Additional Information (Optional)',
    'demo.messagePlaceholder': 'Tell us about your requirements or specific features you\'re interested in...',
    'demo.selectedPlatform': 'Selected Platform:',
    'demo.cancel': 'Cancel',
    'demo.submit': 'Submit Demo Request',
    'demo.success': 'Demo Request Submitted!',
    'demo.successDesc': 'Our team will contact you within 24 hours to schedule a demo.',
    'demo.error': 'Error',
    'demo.errorDesc': 'Failed to submit demo request. Please try again.',
    
    // Common
    'common.loading': 'Loading...',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.contactUs': 'Contact Us',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'We specialise in Cybersecurity and IoT solutions tailored to your needs. Select a service area below to learn more.',
    'services.cyber.title': 'Cybersecurity Services',
    'services.cyber.desc': 'Proactive defenses, managed security, and compliance guidance.',
    'services.cyber.cta': 'Explore Cybersecurity',
    'services.iot.title': 'IoT Services',
    'services.iot.desc': 'Secure device integration, edge computing, and analytics.',
    'services.iot.cta': 'Explore IoT',
    
    // About Page
    'about.title': 'About IRONHEX',
    'about.subtitle': 'Safeguarding What Matters, Today and Beyond',
    'about.intro': 'Founded on expertise, driven by innovation, and committed to a secure digital future.',
    'about.story.title': 'Our Story: Born from Vision and Expertise',
    'about.story.p1': 'IRONHEX was founded in Tunisia in 2025 by two visionary female engineers, each bringing a unique and powerful skillset to the burgeoning fields of cybersecurity and the Internet of Things (IoT). Their shared passion for innovation and an unwavering commitment to digital security laid the groundwork for a company designed to protect and empower businesses in an increasingly connected world.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide cutting-edge cybersecurity and intelligent IoT solutions that empower businesses to thrive securely in a complex digital landscape, fostering innovation while ensuring data integrity and privacy.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the leading trusted partner in digital security and IoT innovation across Tunisia and beyond, shaping a future where technology is both powerful and inherently safe for everyone.',
    'about.founders.title': 'Meet Our Founders',
    'about.founder1.name': 'Imen Chihi',
    'about.founder1.role': 'Co-Founder & CISO',
    'about.founder1.desc': 'A brilliant mind in cybersecurity, Imen leads IRONHEX\'s defense strategies, ensuring our clients and their assets are protected against the most sophisticated digital threats. Her expertise spans threat intelligence, incident response, and secure architecture design.',
    'about.founder2.name': 'Arij Saleh',
    'about.founder2.role': 'Co-Founder & CTO',
    'about.founder2.desc': 'Arij is the driving force behind IRONHEX\'s innovative IoT solutions. With a deep understanding of connected ecosystems, she architects smart, efficient, and scalable IoT deployments that transform businesses and industries.',
    'about.journey.title': 'Join Our Journey',
    'about.journey.desc': 'We are always looking for passionate talent to join our growing team. Explore career opportunities or get in touch to learn more about how we can help secure your digital world.',
    'about.journey.cta': 'Contact Us',
    
    // Cybersecurity Page
    'cyber.hero.title': 'Fortify Your Digital Fortress',
    'cyber.hero.desc': 'IRONHEX provides comprehensive cybersecurity solutions to protect your business from evolving threats and ensure digital resilience.',
    'cyber.hero.offerings': 'Our Offerings',
    'cyber.hero.consultation': 'Get a Consultation',
    'cyber.intro.title': 'Proactive Defense in a Complex Digital Landscape',
    'cyber.intro.p1': 'In today\'s interconnected world, cybersecurity is not just a necessity; it\'s the foundation of business continuity and trust. IRONHEX offers a full spectrum of cybersecurity services designed to identify, protect, detect, respond, and recover from cyber threats.',
    'cyber.intro.p2': 'We combine cutting-edge technology with expert human intelligence to build multi-layered defenses that safeguard your data, systems, and reputation against sophisticated attacks.',
    'cyber.services.title': 'Our Cybersecurity Service Spectrum',
    'cyber.service1.title': 'Managed Security Services',
    'cyber.service1.desc': '24/7 monitoring, threat detection, and rapid response by our Security Operations Center (SOC) experts.',
    'cyber.service2.title': 'Vulnerability Management',
    'cyber.service2.desc': 'Regular scanning, penetration testing, and risk assessments to identify and mitigate security weaknesses.',
    'cyber.service3.title': 'Cloud Security',
    'cyber.service3.desc': 'Secure your cloud infrastructure (AWS, Azure, GCP), applications, and data with robust controls.',
    'cyber.service4.title': 'Endpoint Protection',
    'cyber.service4.desc': 'Advanced protection for all devices, from laptops to servers, against malware, ransomware, and zero-day threats.',
    'cyber.service5.title': 'Identity & Access Management (IAM)',
    'cyber.service5.desc': 'Control who accesses what, enforce multi-factor authentication, and manage user identities securely.',
    'cyber.service6.title': 'Compliance & Regulatory Support',
    'cyber.service6.desc': 'Navigate complex regulatory landscapes (GDPR, HIPAA, ISO 27001) with our expert guidance and solutions.',
    
    // IoT Page
    'iot.hero.title': 'Secure & Seamless IoT Integration',
    'iot.hero.desc': 'Unlock the full potential of your connected devices with IRONHEX\'s intelligent IoT solutions, designed for security and efficiency.',
    'iot.hero.features': 'Explore Features',
    'iot.hero.consultation': 'Get a Consultation',
    'iot.intro.title': 'Transform Your Business with Smart IoT',
    'iot.intro.p1': 'The Internet of Things (IoT) is revolutionizing industries by connecting physical devices to the internet, enabling them to collect and exchange data. At IRONHEX, we empower your business to harness this power through secure, scalable, and intelligent IoT solutions.',
    'iot.intro.p2': 'From smart infrastructure to industrial automation, our experts design, implement, and manage IoT ecosystems that drive efficiency, innovation, and growth while ensuring robust security from edge to cloud.',
    'iot.services.title': 'Our Comprehensive IoT Service Offerings',
    'iot.service1.title': 'IoT Strategy & Consulting',
    'iot.service1.desc': 'Develop a clear IoT roadmap aligned with your business objectives, from device selection to platform integration.',
    'iot.service2.title': 'Secure IoT Device Management',
    'iot.service2.desc': 'Ensure the secure provisioning, monitoring, and updating of all your connected devices throughout their lifecycle.',
    'iot.service3.title': 'Cloud Integration & Data Analytics',
    'iot.service3.desc': 'Seamlessly connect your IoT devices to cloud platforms and derive actionable insights from collected data.',
    'iot.service4.title': 'IoT Security & Compliance',
    'iot.service4.desc': 'Implement multi-layered security protocols and ensure compliance with industry standards to protect your IoT ecosystem.',
    'iot.service5.title': 'Edge Computing Solutions',
    'iot.service5.desc': 'Process data closer to the source for real-time decision-making, reduced latency, and enhanced security.',
    'iot.service6.title': 'Industrial IoT (IIoT)',
    'iot.service6.desc': 'Optimize manufacturing, supply chain, and asset management with robust and secure IIoT implementations.',
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about IRONHEX services',
    'faq.cat.general': 'General Information',
    'faq.cat.services': 'Services & Support',
    'faq.cat.technical': 'Technical Questions',
    'faq.cat.billing': 'Pricing & Billing',
    'faq.questions': 'question',
    'faq.questions_plural': 'questions',
    'faq.cta.title': 'Still have questions?',
    'faq.cta.desc': 'Our team is here to help. Contact us for personalized assistance.',
    'faq.cta.button': 'Contact Us',
    
    'faq.q1': 'What services does IRONHEX provide?',
    'faq.a1': 'IRONHEX specializes in comprehensive cybersecurity solutions and IoT services. We offer penetration testing, security audits, vulnerability assessments, IoT device management, and custom software solutions for enterprise clients.',
    'faq.q2': 'How can I get started with IRONHEX services?',
    'faq.a2': 'Getting started is easy! Simply contact us through our contact form, email, or phone. Our team will schedule a consultation to understand your requirements and propose the best solution for your needs.',
    'faq.q3': 'Do you provide 24/7 support?',
    'faq.a3': 'Yes, we offer 24/7 support for our enterprise clients and managed service customers. Our support team is always available to address critical security incidents and provide technical assistance.',
    'faq.q4': 'What industries do you serve?',
    'faq.a4': 'We serve a wide range of industries including financial services, healthcare, manufacturing, retail, government agencies, and technology companies. Our solutions are tailored to meet industry-specific compliance and security requirements.',
    'faq.q5': 'How long does a security audit take?',
    'faq.a5': 'The duration of a security audit depends on the scope and complexity of your infrastructure. Typically, a comprehensive audit takes 2-4 weeks. We provide a detailed timeline during the initial consultation.',
    'faq.q6': 'What is penetration testing?',
    'faq.a6': 'Penetration testing is a simulated cyber attack on your system to identify vulnerabilities before malicious actors can exploit them. Our certified ethical hackers use industry-standard methodologies to test your security posture.',
    'faq.q7': 'Do you offer training services?',
    'faq.a7': 'Yes, we provide security awareness training for employees, technical training for IT teams, and specialized cybersecurity certification preparation courses.',
    'faq.q8': 'What is your pricing model?',
    'faq.a8': 'We offer flexible pricing models including project-based, monthly retainers, and custom packages. Pricing depends on the scope of services, duration, and specific requirements. Contact us for a detailed quote.',
    'faq.q9': 'Are your solutions compliant with regulations?',
    'faq.a9': 'Yes, our solutions are designed to help you meet various compliance requirements including GDPR, HIPAA, PCI-DSS, ISO 27001, and local regulations. We can assist with compliance audits and documentation.',
    'faq.q10': 'Can you help with incident response?',
    'faq.a10': 'Absolutely. We offer rapid incident response services to help you contain, investigate, and recover from security breaches. Our team can be engaged on-demand or through a retainer for priority response.',
    'faq.q11': 'What makes IRONHEX different from competitors?',
    'faq.a11': 'IRONHEX combines deep technical expertise with a customer-first approach. We provide tailored solutions, maintain transparency throughout engagements, and ensure knowledge transfer to empower your team.',
    'faq.q12': 'Do you provide remote or on-site services?',
    'faq.a12': 'We offer both remote and on-site services depending on your requirements. Many assessments can be conducted remotely, while others may require on-site presence for physical security testing or sensitive environments.',
    
    // Tunisian Regulations Page
    'reg.title': 'Tunisian Cybersecurity Regulations',
    'reg.subtitle': 'Understanding Tunisia\'s legal framework for cybersecurity and data protection',
    'reg.alert.title': 'Regulatory Compliance',
    'reg.alert.desc': 'IRONHEX ensures all services comply with Tunisian cybersecurity laws and international standards.',
    
    'reg.section1.title': 'Data Protection Law',
    'reg.section1.subtitle': 'Organic Law No. 2004-63 on the Protection of Personal Data',
    'reg.section1.p1': 'Tunisia\'s data protection law establishes the framework for collecting, processing, and storing personal data. Organizations must obtain explicit consent before processing personal information and implement appropriate security measures to protect data.',
    'reg.section1.requirements': 'Key Requirements:',
    'reg.section1.req1': 'Registration with the National Authority for Personal Data Protection (INPDP)',
    'reg.section1.req2': 'Implementation of technical and organizational security measures',
    'reg.section1.req3': 'Data breach notification within 72 hours',
    'reg.section1.req4': 'Data subject rights including access, rectification, and deletion',
    
    'reg.section2.title': 'Cybercrime Law',
    'reg.section2.subtitle': 'Law No. 2004-5 on Computer Security and Data Protection',
    'reg.section2.p1': 'This law addresses cybercrime and establishes penalties for unauthorized access to computer systems, data theft, and other cyber offenses. It provides the legal foundation for prosecuting cybercriminals and protecting critical information infrastructure.',
    'reg.section2.offenses': 'Covered Offenses:',
    'reg.section2.off1': 'Unauthorized access to computer systems',
    'reg.section2.off2': 'Data theft and fraud',
    'reg.section2.off3': 'Distribution of malware',
    'reg.section2.off4': 'Cyber harassment and online threats',
    
    'reg.section3.title': 'Electronic Communications Regulation',
    'reg.section3.subtitle': 'Telecommunications Code and INTT Regulations',
    'reg.section3.p1': 'The National Telecommunications Institute of Tunisia (INTT) regulates electronic communications and network security. Service providers must comply with technical standards and security requirements.',
    
    'reg.section4.title': 'How IRONHEX Ensures Compliance',
    'reg.section4.p1': 'IRONHEX works with organizations to ensure full compliance with Tunisian cybersecurity regulations:',
    'reg.section4.service1.title': 'Compliance Audits',
    'reg.section4.service1.desc': 'Comprehensive assessments of your current compliance status against Tunisian regulations',
    'reg.section4.service2.title': 'Policy Development',
    'reg.section4.service2.desc': 'Creation of policies and procedures aligned with legal requirements',
    'reg.section4.service3.title': 'Security Implementation',
    'reg.section4.service3.desc': 'Deployment of technical controls to meet regulatory security standards',
    'reg.section4.service4.title': 'Ongoing Monitoring',
    'reg.section4.service4.desc': 'Continuous compliance monitoring and reporting',
    
    'reg.disclaimer.title': 'Disclaimer:',
    'reg.disclaimer.text': 'This information is provided for general guidance only and does not constitute legal advice. For specific legal questions, please consult with a qualified legal professional.',
    
    'reg.cta.title': 'Need Help with Compliance?',
    'reg.cta.desc': 'Contact our experts to ensure your organization meets all regulatory requirements',
    'reg.cta.button': 'Get Started',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.cybersecurity': 'Cybersécurité',
    'nav.iot': 'Solutions IoT',
    'nav.software': 'Solutions Logicielles',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.regulations': 'Réglementations Tunisiennes',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'Fournir des solutions robustes de cybersécurité et IoT innovantes pour sécuriser votre avenir numérique.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.ourServices': 'Nos Services',
    'footer.getInTouch': 'Contactez-nous',
    'footer.phone': 'Téléphone',
    'footer.address': 'Adresse',
    'footer.location': 'Mégrine, Ben Arous',
    'footer.country': 'Tunisie',
    'footer.contactUs': 'Nous Contacter',
    'footer.rights': 'Tous droits réservés.',
    
    // Home
    'home.hero.title': 'Sécurité Inébranlable pour un Monde Interconnecté',
    'home.hero.description': 'Protéger votre entreprise avec une cybersécurité avancée et des solutions IoT intelligentes',
    'home.hero.cta': 'Obtenir une Évaluation de Sécurité Gratuite',
    'home.services.title': 'Nos Services Principaux',
    'home.services.cyber.title': 'Services de Cybersécurité',
    'home.services.cyber.desc': 'Défense proactive contre les menaces numériques évolutives',
    'home.services.iot.title': 'Services IoT',
    'home.services.iot.desc': 'Intégration sécurisée et transparente des appareils intelligents',
    'home.services.managed.title': 'Sécurité Gérée & Support',
    'home.services.managed.desc': 'Surveillance 24/7, réponse rapide et conseils d\'experts',
    'home.testimonials.title': 'Ce que disent les clients',
    'home.testimonials.1': '"IRONHEX a sécurisé notre déploiement IoT et amélioré la surveillance - leur équipe est de premier ordre."',
    'home.testimonials.1.author': '- CTO, Acme Corp',
    'home.testimonials.2': '"Les temps de réponse et l\'expertise sont exceptionnels. Recommandé."',
    'home.testimonials.2.author': '- Responsable IT, Beta Ltd',
    'home.partners.title': 'Nos partenaires',
    
    // Contact Form
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'contact.sending': 'Envoi...',
    
    // Software Solutions
    'software.title': 'Solutions Web Prêtes à l\'Emploi',
    'software.subtitle': 'Plateformes web professionnelles et entièrement fonctionnelles prêtes à déployer. Demandez une démo en direct.',
    'software.features': 'Fonctionnalités Clés:',
    'software.technologies': 'Technologies:',
    'software.requestDemo': 'Demander une Démo',
    'software.customTitle': 'Besoin d\'une Solution Web Personnalisée?',
    'software.customDesc': 'Notre équipe peut développer une plateforme web sur mesure spécialement conçue pour vos besoins uniques',
    'software.customCta': 'Contactez-nous pour un Développement Personnalisé',
    
    // Demo Request
    'demo.title': 'Demander une Démo',
    'demo.description': 'Remplissez vos coordonnées et nous planifierons une session de démonstration personnalisée.',
    'demo.fullName': 'Nom Complet',
    'demo.email': 'Adresse Email',
    'demo.phone': 'Numéro de Téléphone',
    'demo.company': 'Nom de l\'Entreprise (Optionnel)',
    'demo.message': 'Informations Supplémentaires (Optionnel)',
    'demo.messagePlaceholder': 'Parlez-nous de vos besoins ou des fonctionnalités spécifiques qui vous intéressent...',
    'demo.selectedPlatform': 'Plateforme Sélectionnée:',
    'demo.cancel': 'Annuler',
    'demo.submit': 'Soumettre la Demande',
    'demo.success': 'Demande de Démo Soumise!',
    'demo.successDesc': 'Notre équipe vous contactera dans les 24 heures pour planifier une démo.',
    'demo.error': 'Erreur',
    'demo.errorDesc': 'Échec de la soumission de la demande de démo. Veuillez réessayer.',
    
    // Common
    'common.loading': 'Chargement...',
    'common.readMore': 'Lire Plus',
    'common.learnMore': 'En Savoir Plus',
    'common.getStarted': 'Commencer',
    'common.contactUs': 'Nous Contacter',
    
    // Services Page
    'services.title': 'Nos Services',
    'services.subtitle': 'Nous sommes spécialisés dans les solutions de cybersécurité et IoT adaptées à vos besoins. Sélectionnez un domaine de service ci-dessous pour en savoir plus.',
    'services.cyber.title': 'Services de Cybersécurité',
    'services.cyber.desc': 'Défenses proactives, sécurité gérée et conseils en conformité.',
    'services.cyber.cta': 'Explorer la Cybersécurité',
    'services.iot.title': 'Services IoT',
    'services.iot.desc': 'Intégration sécurisée des appareils, edge computing et analytique.',
    'services.iot.cta': 'Explorer l\'IoT',
    
    // About Page
    'about.title': 'À Propos d\'IRONHEX',
    'about.subtitle': 'Sécuriser Demain, Aujourd\'hui',
    'about.intro': 'Fondé sur l\'expertise, porté par l\'innovation et engagé pour un avenir numérique sécurisé.',
    'about.story.title': 'Notre Histoire: Née de la Vision et de l\'Expertise',
    'about.story.p1': 'IRONHEX a été fondée en Tunisie en 2025 par deux ingénieures visionnaires, chacune apportant un ensemble de compétences unique et puissant aux domaines émergents de la cybersécurité et de l\'Internet des Objets (IoT). Leur passion commune pour l\'innovation et leur engagement indéfectible envers la sécurité numérique ont jeté les bases d\'une entreprise conçue pour protéger et autonomiser les entreprises dans un monde de plus en plus connecté.',
    'about.mission.title': 'Notre Mission',
    'about.mission.desc': 'Fournir des solutions de cybersécurité de pointe et des solutions IoT intelligentes qui permettent aux entreprises de prospérer en toute sécurité dans un paysage numérique complexe, favorisant l\'innovation tout en garantissant l\'intégrité et la confidentialité des données.',
    'about.vision.title': 'Notre Vision',
    'about.vision.desc': 'Être le partenaire de confiance leader en sécurité numérique et innovation IoT en Tunisie et au-delà, façonnant un avenir où la technologie est à la fois puissante et intrinsèquement sûre pour tous.',
    'about.founders.title': 'Rencontrez Nos Fondatrices',
    'about.founder1.name': 'Imen Chihi',
    'about.founder1.role': 'Co-Fondatrice & CISO',
    'about.founder1.desc': 'Un esprit brillant en cybersécurité, Imen dirige les stratégies de défense d\'IRONHEX, garantissant que nos clients et leurs actifs sont protégés contre les menaces numériques les plus sophistiquées. Son expertise couvre le renseignement sur les menaces, la réponse aux incidents et la conception d\'architecture sécurisée.',
    'about.founder2.name': 'Arij Saleh',
    'about.founder2.role': 'Co-Fondatrice & CTO',
    'about.founder2.desc': 'Arij est la force motrice derrière les solutions IoT innovantes d\'IRONHEX. Avec une compréhension approfondie des écosystèmes connectés, elle conçoit des déploiements IoT intelligents, efficaces et évolutifs qui transforment les entreprises et les industries.',
    'about.journey.title': 'Rejoignez Notre Aventure',
    'about.journey.desc': 'Nous sommes toujours à la recherche de talents passionnés pour rejoindre notre équipe en pleine croissance. Explorez les opportunités de carrière ou contactez-nous pour en savoir plus sur la façon dont nous pouvons sécuriser votre monde numérique.',
    'about.journey.cta': 'Nous Contacter',
    
    // Cybersecurity Page
    'cyber.hero.title': 'Fortifiez Votre Forteresse Numérique',
    'cyber.hero.desc': 'IRONHEX fournit des solutions de cybersécurité complètes pour protéger votre entreprise contre les menaces évolutives et garantir la résilience numérique.',
    'cyber.hero.offerings': 'Nos Offres',
    'cyber.hero.consultation': 'Obtenir une Consultation',
    'cyber.intro.title': 'Défense Proactive dans un Paysage Numérique Complexe',
    'cyber.intro.p1': 'Dans le monde interconnecté d\'aujourd\'hui, la cybersécurité n\'est pas seulement une nécessité; c\'est le fondement de la continuité des activités et de la confiance. IRONHEX offre un spectre complet de services de cybersécurité conçus pour identifier, protéger, détecter, répondre et récupérer des menaces cybernétiques.',
    'cyber.intro.p2': 'Nous combinons une technologie de pointe avec l\'intelligence humaine experte pour construire des défenses multicouches qui protègent vos données, systèmes et réputation contre les attaques sophistiquées.',
    'cyber.services.title': 'Notre Spectre de Services de Cybersécurité',
    'cyber.service1.title': 'Services de Sécurité Gérés',
    'cyber.service1.desc': 'Surveillance 24/7, détection des menaces et réponse rapide par nos experts du Centre d\'Opérations de Sécurité (SOC).',
    'cyber.service2.title': 'Gestion des Vulnérabilités',
    'cyber.service2.desc': 'Analyse régulière, tests de pénétration et évaluations des risques pour identifier et atténuer les faiblesses de sécurité.',
    'cyber.service3.title': 'Sécurité Cloud',
    'cyber.service3.desc': 'Sécurisez votre infrastructure cloud (AWS, Azure, GCP), applications et données avec des contrôles robustes.',
    'cyber.service4.title': 'Protection des Points de Terminaison',
    'cyber.service4.desc': 'Protection avancée pour tous les appareils, des ordinateurs portables aux serveurs, contre les logiciels malveillants, ransomwares et menaces zero-day.',
    'cyber.service5.title': 'Gestion des Identités et des Accès (IAM)',
    'cyber.service5.desc': 'Contrôlez qui accède à quoi, appliquez l\'authentification multifacteur et gérez les identités des utilisateurs en toute sécurité.',
    'cyber.service6.title': 'Support Conformité & Réglementaire',
    'cyber.service6.desc': 'Naviguez dans les paysages réglementaires complexes (RGPD, HIPAA, ISO 27001) avec nos conseils et solutions d\'experts.',
    
    // IoT Page
    'iot.hero.title': 'Intégration IoT Sécurisée et Transparente',
    'iot.hero.desc': 'Libérez tout le potentiel de vos appareils connectés avec les solutions IoT intelligentes d\'IRONHEX, conçues pour la sécurité et l\'efficacité.',
    'iot.hero.features': 'Explorer les Fonctionnalités',
    'iot.hero.consultation': 'Obtenir une Consultation',
    'iot.intro.title': 'Transformez Votre Entreprise avec l\'IoT Intelligent',
    'iot.intro.p1': 'L\'Internet des Objets (IoT) révolutionne les industries en connectant les appareils physiques à Internet, leur permettant de collecter et d\'échanger des données. Chez IRONHEX, nous permettons à votre entreprise d\'exploiter ce pouvoir grâce à des solutions IoT sécurisées, évolutives et intelligentes.',
    'iot.intro.p2': 'De l\'infrastructure intelligente à l\'automatisation industrielle, nos experts conçoivent, mettent en œuvre et gèrent des écosystèmes IoT qui favorisent l\'efficacité, l\'innovation et la croissance tout en garantissant une sécurité robuste de la périphérie au cloud.',
    'iot.services.title': 'Nos Offres Complètes de Services IoT',
    'iot.service1.title': 'Stratégie et Conseil IoT',
    'iot.service1.desc': 'Développez une feuille de route IoT claire alignée sur vos objectifs commerciaux, de la sélection des appareils à l\'intégration de la plateforme.',
    'iot.service2.title': 'Gestion Sécurisée des Appareils IoT',
    'iot.service2.desc': 'Assurez le provisionnement, la surveillance et la mise à jour sécurisés de tous vos appareils connectés tout au long de leur cycle de vie.',
    'iot.service3.title': 'Intégration Cloud et Analytique de Données',
    'iot.service3.desc': 'Connectez de manière transparente vos appareils IoT aux plateformes cloud et tirez des informations exploitables des données collectées.',
    'iot.service4.title': 'Sécurité et Conformité IoT',
    'iot.service4.desc': 'Mettez en œuvre des protocoles de sécurité multicouches et assurez la conformité aux normes de l\'industrie pour protéger votre écosystème IoT.',
    'iot.service5.title': 'Solutions d\'Edge Computing',
    'iot.service5.desc': 'Traitez les données plus près de la source pour une prise de décision en temps réel, une latence réduite et une sécurité améliorée.',
    'iot.service6.title': 'IoT Industriel (IIoT)',
    'iot.service6.desc': 'Optimisez la fabrication, la chaîne d\'approvisionnement et la gestion des actifs avec des implémentations IIoT robustes et sécurisées.',
    
    // FAQ Page
    'faq.title': 'Foire Aux Questions',
    'faq.subtitle': 'Trouvez des réponses aux questions courantes sur les services IRONHEX',
    'faq.cat.general': 'Informations Générales',
    'faq.cat.services': 'Services & Support',
    'faq.cat.technical': 'Questions Techniques',
    'faq.cat.billing': 'Tarification & Facturation',
    'faq.questions': 'question',
    'faq.questions_plural': 'questions',
    'faq.cta.title': 'Vous avez encore des questions?',
    'faq.cta.desc': 'Notre équipe est là pour vous aider. Contactez-nous pour une assistance personnalisée.',
    'faq.cta.button': 'Nous Contacter',
    
    'faq.q1': 'Quels services IRONHEX propose-t-il?',
    'faq.a1': 'IRONHEX est spécialisé dans les solutions complètes de cybersécurité et les services IoT. Nous proposons des tests de pénétration, des audits de sécurité, des évaluations de vulnérabilité, la gestion d\'appareils IoT et des solutions logicielles personnalisées pour les clients d\'entreprise.',
    'faq.q2': 'Comment puis-je commencer avec les services IRONHEX?',
    'faq.a2': 'C\'est facile de commencer! Contactez-nous simplement via notre formulaire de contact, par e-mail ou par téléphone. Notre équipe planifiera une consultation pour comprendre vos besoins et proposer la meilleure solution.',
    'faq.q3': 'Offrez-vous un support 24h/24 et 7j/7?',
    'faq.a3': 'Oui, nous offrons un support 24h/24 et 7j/7 à nos clients d\'entreprise et aux clients de services gérés. Notre équipe d\'assistance est toujours disponible pour traiter les incidents de sécurité critiques et fournir une assistance technique.',
    'faq.q4': 'Quels secteurs servez-vous?',
    'faq.a4': 'Nous servons un large éventail de secteurs, notamment les services financiers, la santé, la fabrication, le commerce de détail, les agences gouvernementales et les entreprises technologiques. Nos solutions sont adaptées pour répondre aux exigences de conformité et de sécurité spécifiques à l\'industrie.',
    'faq.q5': 'Combien de temps dure un audit de sécurité?',
    'faq.a5': 'La durée d\'un audit de sécurité dépend de la portée et de la complexité de votre infrastructure. Généralement, un audit complet prend 2 à 4 semaines. Nous fournissons un calendrier détaillé lors de la consultation initiale.',
    'faq.q6': 'Qu\'est-ce qu\'un test de pénétration?',
    'faq.a6': 'Le test de pénétration est une attaque cybernétique simulée sur votre système pour identifier les vulnérabilités avant que des acteurs malveillants ne puissent les exploiter. Nos hackers éthiques certifiés utilisent des méthodologies standard de l\'industrie pour tester votre posture de sécurité.',
    'faq.q7': 'Offrez-vous des services de formation?',
    'faq.a7': 'Oui, nous proposons des formations de sensibilisation à la sécurité pour les employés, des formations techniques pour les équipes informatiques et des cours de préparation aux certifications spécialisées en cybersécurité.',
    'faq.q8': 'Quel est votre modèle de tarification?',
    'faq.a8': 'Nous proposons des modèles de tarification flexibles, y compris basés sur des projets, des contrats mensuels et des forfaits personnalisés. La tarification dépend de la portée des services, de la durée et des exigences spécifiques. Contactez-nous pour un devis détaillé.',
    'faq.q9': 'Vos solutions sont-elles conformes aux réglementations?',
    'faq.a9': 'Oui, nos solutions sont conçues pour vous aider à répondre à diverses exigences de conformité, notamment le RGPD, HIPAA, PCI-DSS, ISO 27001 et les réglementations locales. Nous pouvons vous aider avec les audits de conformité et la documentation.',
    'faq.q10': 'Pouvez-vous aider en cas d\'incident?',
    'faq.a10': 'Absolument. Nous offrons des services de réponse rapide aux incidents pour vous aider à contenir, enquêter et récupérer des violations de sécurité. Notre équipe peut être engagée à la demande ou via un contrat pour une réponse prioritaire.',
    'faq.q11': 'Qu\'est-ce qui distingue IRONHEX de ses concurrents?',
    'faq.a11': 'IRONHEX combine une expertise technique approfondie avec une approche centrée sur le client. Nous fournissons des solutions sur mesure, maintenons la transparence tout au long des engagements et assurons le transfert de connaissances pour autonomiser votre équipe.',
    'faq.q12': 'Fournissez-vous des services à distance ou sur site?',
    'faq.a12': 'Nous offrons des services à distance et sur site en fonction de vos besoins. De nombreuses évaluations peuvent être effectuées à distance, tandis que d\'autres peuvent nécessiter une présence sur site pour des tests de sécurité physique ou des environnements sensibles.',
    
    // Tunisian Regulations Page
    'reg.title': 'Réglementations Tunisiennes en Cybersécurité',
    'reg.subtitle': 'Comprendre le cadre juridique tunisien pour la cybersécurité et la protection des données',
    'reg.alert.title': 'Conformité Réglementaire',
    'reg.alert.desc': 'IRONHEX garantit que tous les services sont conformes aux lois tunisiennes sur la cybersécurité et aux normes internationales.',
    
    'reg.section1.title': 'Loi sur la Protection des Données',
    'reg.section1.subtitle': 'Loi Organique n° 2004-63 sur la Protection des Données Personnelles',
    'reg.section1.p1': 'La loi tunisienne sur la protection des données établit le cadre pour la collecte, le traitement et le stockage des données personnelles. Les organisations doivent obtenir un consentement explicite avant de traiter des informations personnelles et mettre en œuvre des mesures de sécurité appropriées pour protéger les données.',
    'reg.section1.requirements': 'Exigences Clés:',
    'reg.section1.req1': 'Enregistrement auprès de l\'Instance Nationale de Protection des Données Personnelles (INPDP)',
    'reg.section1.req2': 'Mise en œuvre de mesures de sécurité techniques et organisationnelles',
    'reg.section1.req3': 'Notification de violation de données dans les 72 heures',
    'reg.section1.req4': 'Droits des personnes concernées incluant l\'accès, la rectification et la suppression',
    
    'reg.section2.title': 'Loi sur la Cybercriminalité',
    'reg.section2.subtitle': 'Loi n° 2004-5 sur la Sécurité Informatique et la Protection des Données',
    'reg.section2.p1': 'Cette loi traite de la cybercriminalité et établit des sanctions pour l\'accès non autorisé aux systèmes informatiques, le vol de données et d\'autres infractions cybernétiques. Elle fournit la base juridique pour poursuivre les cybercriminels et protéger les infrastructures d\'information critiques.',
    'reg.section2.offenses': 'Infractions Couvertes:',
    'reg.section2.off1': 'Accès non autorisé aux systèmes informatiques',
    'reg.section2.off2': 'Vol de données et fraude',
    'reg.section2.off3': 'Distribution de logiciels malveillants',
    'reg.section2.off4': 'Harcèlement cybernétique et menaces en ligne',
    
    'reg.section3.title': 'Réglementation des Communications Électroniques',
    'reg.section3.subtitle': 'Code des Télécommunications et Règlements de l\'INTT',
    'reg.section3.p1': 'L\'Instance Nationale des Télécommunications de Tunisie (INTT) réglemente les communications électroniques et la sécurité des réseaux. Les fournisseurs de services doivent se conformer aux normes techniques et aux exigences de sécurité.',
    
    'reg.section4.title': 'Comment IRONHEX Assure la Conformité',
    'reg.section4.p1': 'IRONHEX travaille avec les organisations pour garantir une conformité totale avec les réglementations tunisiennes en cybersécurité:',
    'reg.section4.service1.title': 'Audits de Conformité',
    'reg.section4.service1.desc': 'Évaluations complètes de votre statut de conformité actuel par rapport aux réglementations tunisiennes',
    'reg.section4.service2.title': 'Développement de Politiques',
    'reg.section4.service2.desc': 'Création de politiques et de procédures alignées sur les exigences légales',
    'reg.section4.service3.title': 'Mise en Œuvre de la Sécurité',
    'reg.section4.service3.desc': 'Déploiement de contrôles techniques pour répondre aux normes de sécurité réglementaires',
    'reg.section4.service4.title': 'Surveillance Continue',
    'reg.section4.service4.desc': 'Surveillance et reporting continus de la conformité',
    
    'reg.disclaimer.title': 'Avertissement:',
    'reg.disclaimer.text': 'Ces informations sont fournies à titre indicatif uniquement et ne constituent pas un conseil juridique. Pour des questions juridiques spécifiques, veuillez consulter un professionnel juridique qualifié.',
    
    'reg.cta.title': 'Besoin d\'Aide pour la Conformité?',
    'reg.cta.desc': 'Contactez nos experts pour vous assurer que votre organisation respecte toutes les exigences réglementaires',
    'reg.cta.button': 'Commencer',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.cybersecurity': 'الأمن السيبراني',
    'nav.iot': 'حلول إنترنت الأشياء',
    'nav.software': 'الحلول البرمجية',
    'nav.contact': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.regulations': 'اللوائح التونسية',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'توفير حلول قوية للأمن السيبراني وحلول مبتكرة لإنترنت الأشياء لتأمين مستقبلك الرقمي.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.ourServices': 'خدماتنا',
    'footer.getInTouch': 'تواصل معنا',
    'footer.phone': 'الهاتف',
    'footer.address': 'العنوان',
    'footer.location': 'المقرن، بن عروس',
    'footer.country': 'تونس',
    'footer.contactUs': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    
    // Home
    'home.hero.title': 'أمان لا يقهر لعالم متصل',
    'home.hero.description': 'حماية عملك بأمن سيبراني متقدم وحلول إنترنت الأشياء الذكية',
    'home.hero.cta': 'احصل على تقييم أمني مجاني',
    'home.services.title': 'خدماتنا الأساسية',
    'home.services.cyber.title': 'خدمات الأمن السيبراني',
    'home.services.cyber.desc': 'دفاع استباقي ضد التهديدات الرقمية المتطورة',
    'home.services.iot.title': 'خدمات إنترنت الأشياء',
    'home.services.iot.desc': 'تكامل آمن وسلس للأجهزة الذكية',
    'home.services.managed.title': 'الأمن المُدار والدعم',
    'home.services.managed.desc': 'مراقبة على مدار الساعة، استجابة سريعة، وإرشادات متخصصة',
    'home.testimonials.title': 'ماذا يقول العملاء',
    'home.testimonials.1': '"قامت IRONHEX بتأمين طرحنا لإنترنت الأشياء وتحسين المراقبة - فريقهم من الدرجة الأولى."',
    'home.testimonials.1.author': '- المدير التقني، Acme Corp',
    'home.testimonials.2': '"أوقات الاستجابة والخبرة استثنائية. موصى به."',
    'home.testimonials.2.author': '- رئيس قسم تكنولوجيا المعلومات، Beta Ltd',
    'home.partners.title': 'شركاؤنا',
    
    // Contact Form
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال',
    'contact.sending': 'جاري الإرسال...',
    
    // Software Solutions
    'software.title': 'حلول مواقع جاهزة',
    'software.subtitle': 'منصات ويب احترافية وكاملة الوظائف جاهزة للنشر. اطلب عرضاً توضيحياً مباشراً.',
    'software.features': 'الميزات الرئيسية:',
    'software.technologies': 'التقنيات:',
    'software.requestDemo': 'طلب عرض توضيحي',
    'software.customTitle': 'هل تحتاج إلى حل ويب مخصص؟',
    'software.customDesc': 'يمكن لفريقنا تطوير منصة ويب مخصصة مصممة خصيصاً لاحتياجات عملك الفريدة',
    'software.customCta': 'اتصل بنا للتطوير المخصص',
    
    // Demo Request
    'demo.title': 'طلب عرض توضيحي',
    'demo.description': 'املأ بياناتك وسنقوم بجدولة جلسة عرض توضيحي شخصية.',
    'demo.fullName': 'الاسم الكامل',
    'demo.email': 'عنوان البريد الإلكتروني',
    'demo.phone': 'رقم الهاتف',
    'demo.company': 'اسم الشركة (اختياري)',
    'demo.message': 'معلومات إضافية (اختياري)',
    'demo.messagePlaceholder': 'أخبرنا عن متطلباتك أو الميزات المحددة التي تهمك...',
    'demo.selectedPlatform': 'المنصة المختارة:',
    'demo.cancel': 'إلغاء',
    'demo.submit': 'إرسال الطلب',
    'demo.success': 'تم إرسال طلب العرض التوضيحي!',
    'demo.successDesc': 'سيتصل بك فريقنا خلال 24 ساعة لجدولة العرض التوضيحي.',
    'demo.error': 'خطأ',
    'demo.errorDesc': 'فشل إرسال طلب العرض التوضيحي. يرجى المحاولة مرة أخرى.',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.readMore': 'اقرأ المزيد',
    'common.learnMore': 'اعرف المزيد',
    'common.getStarted': 'ابدأ الآن',
    'common.contactUs': 'اتصل بنا',
    
    // Services Page
    'services.title': 'خدماتنا',
    'services.subtitle': 'نحن متخصصون في حلول الأمن السيبراني وإنترنت الأشياء المصممة خصيصًا لتلبية احتياجاتك. اختر مجال خدمة أدناه لمعرفة المزيد.',
    'services.cyber.title': 'خدمات الأمن السيبراني',
    'services.cyber.desc': 'دفاعات استباقية، أمان مُدار، وإرشادات الامتثال.',
    'services.cyber.cta': 'استكشف الأمن السيبراني',
    'services.iot.title': 'خدمات إنترنت الأشياء',
    'services.iot.desc': 'تكامل آمن للأجهزة، الحوسبة الطرفية، والتحليلات.',
    'services.iot.cta': 'استكشف إنترنت الأشياء',
    
    // About Page
    'about.title': 'حول IRONHEX',
    'about.subtitle': 'تأمين الغد، اليوم',
    'about.intro': 'تأسست على الخبرة، مدفوعة بالابتكار، وملتزمة بمستقبل رقمي آمن.',
    'about.story.title': 'قصتنا: وُلدت من الرؤية والخبرة',
    'about.story.p1': 'تأسست IRONHEX في تونس عام 2025 على يد مهندستين صاحبتي رؤية، كل منهما تجلب مجموعة مهارات فريدة وقوية إلى المجالات الناشئة للأمن السيبراني وإنترنت الأشياء (IoT). شغفهما المشترك بالابتكار والتزامهما الثابت بالأمن الرقمي وضع الأساس لشركة مصممة لحماية وتمكين الشركات في عالم متصل بشكل متزايد.',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'تقديم حلول أمن سيبراني متطورة وحلول إنترنت الأشياء الذكية التي تمكن الشركات من الازدهار بأمان في مشهد رقمي معقد، وتعزيز الابتكار مع ضمان سلامة البيانات والخصوصية.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.desc': 'أن نكون الشريك الموثوق الرائد في الأمن الرقمي وابتكار إنترنت الأشياء في تونس وخارجها، وتشكيل مستقبل تكون فيه التكنولوجيا قوية وآمنة بطبيعتها للجميع.',
    'about.founders.title': 'تعرف على مؤسساتنا',
    'about.founder1.name': 'إيمان الشيحي',
    'about.founder1.role': 'مؤسس مشارك ومدير أمن المعلومات',
    'about.founder1.desc': 'عقل متألق في الأمن السيبراني، تقود إيمان استراتيجيات الدفاع في IRONHEX، وتضمن حماية عملائنا وأصولهم من أكثر التهديدات الرقمية تطورًا. تمتد خبرتها عبر استخبارات التهديدات والاستجابة للحوادث وتصميم البنية المعمارية الآمنة.',
    'about.founder2.name': 'أريج صالح',
    'about.founder2.role': 'مؤسس مشارك ومدير التكنولوجيا',
    'about.founder2.desc': 'أريج هي القوة الدافعة وراء حلول إنترنت الأشياء المبتكرة في IRONHEX. مع فهم عميق للنظم البيئية المتصلة، تقوم بتصميم عمليات نشر إنترنت الأشياء الذكية والفعالة والقابلة للتطوير التي تحول الشركات والصناعات.',
    'about.journey.title': 'انضم إلى رحلتنا',
    'about.journey.desc': 'نحن دائمًا نبحث عن مواهب متحمسة للانضمام إلى فريقنا المتنامي. استكشف فرص العمل أو تواصل معنا لمعرفة المزيد حول كيف يمكننا تأمين عالمك الرقمي.',
    'about.journey.cta': 'اتصل بنا',
    
    // Cybersecurity Page
    'cyber.hero.title': 'حصّن قلعتك الرقمية',
    'cyber.hero.desc': 'توفر IRONHEX حلول أمن سيبراني شاملة لحماية عملك من التهديدات المتطورة وضمان المرونة الرقمية.',
    'cyber.hero.offerings': 'عروضنا',
    'cyber.hero.consultation': 'احصل على استشارة',
    'cyber.intro.title': 'دفاع استباقي في مشهد رقمي معقد',
    'cyber.intro.p1': 'في عالم اليوم المترابط، الأمن السيبراني ليس مجرد ضرورة؛ إنه أساس استمرارية الأعمال والثقة. تقدم IRONHEX مجموعة كاملة من خدمات الأمن السيبراني المصممة لتحديد وحماية واكتشاف والاستجابة والتعافي من التهديدات السيبرانية.',
    'cyber.intro.p2': 'نحن نجمع بين التكنولوجيا المتطورة والذكاء البشري الخبير لبناء دفاعات متعددة الطبقات تحمي بياناتك وأنظمتك وسمعتك ضد الهجمات المتطورة.',
    'cyber.services.title': 'طيف خدمات الأمن السيبراني لدينا',
    'cyber.service1.title': 'خدمات الأمن المُدارة',
    'cyber.service1.desc': 'مراقبة 24/7، كشف التهديدات، واستجابة سريعة من قبل خبراء مركز العمليات الأمنية (SOC).',
    'cyber.service2.title': 'إدارة الثغرات',
    'cyber.service2.desc': 'فحص منتظم، اختبار الاختراق، وتقييمات المخاطر لتحديد وتخفيف نقاط الضعف الأمنية.',
    'cyber.service3.title': 'أمن السحابة',
    'cyber.service3.desc': 'تأمين البنية التحتية السحابية الخاصة بك (AWS، Azure، GCP)، والتطبيقات، والبيانات بضوابط قوية.',
    'cyber.service4.title': 'حماية نقاط النهاية',
    'cyber.service4.desc': 'حماية متقدمة لجميع الأجهزة، من أجهزة الكمبيوتر المحمولة إلى الخوادم، ضد البرامج الضارة وبرامج الفدية والتهديدات يوم الصفر.',
    'cyber.service5.title': 'إدارة الهوية والوصول (IAM)',
    'cyber.service5.desc': 'التحكم في من يصل إلى ماذا، وفرض المصادقة متعددة العوامل، وإدارة هويات المستخدمين بشكل آمن.',
    'cyber.service6.title': 'دعم الامتثال والتنظيم',
    'cyber.service6.desc': 'التنقل في المشاهد التنظيمية المعقدة (GDPR، HIPAA، ISO 27001) مع إرشادات وحلول خبرائنا.',
    
    // IoT Page
    'iot.hero.title': 'تكامل إنترنت الأشياء الآمن والسلس',
    'iot.hero.desc': 'أطلق العنان للإمكانات الكاملة لأجهزتك المتصلة مع حلول إنترنت الأشياء الذكية من IRONHEX، المصممة للأمان والكفاءة.',
    'iot.hero.features': 'استكشف الميزات',
    'iot.hero.consultation': 'احصل على استشارة',
    'iot.intro.title': 'حوّل عملك بإنترنت الأشياء الذكي',
    'iot.intro.p1': 'يُحدث إنترنت الأشياء (IoT) ثورة في الصناعات من خلال ربط الأجهزة المادية بالإنترنت، مما يمكنها من جمع وتبادل البيانات. في IRONHEX، نمكن عملك من تسخير هذه القوة من خلال حلول إنترنت الأشياء الآمنة والقابلة للتطوير والذكية.',
    'iot.intro.p2': 'من البنية التحتية الذكية إلى الأتمتة الصناعية، يقوم خبراؤنا بتصميم وتنفيذ وإدارة النظم البيئية لإنترنت الأشياء التي تدفع الكفاءة والابتكار والنمو مع ضمان أمان قوي من الحافة إلى السحابة.',
    'iot.services.title': 'عروض خدمات إنترنت الأشياء الشاملة لدينا',
    'iot.service1.title': 'استراتيجية واستشارات إنترنت الأشياء',
    'iot.service1.desc': 'تطوير خارطة طريق واضحة لإنترنت الأشياء تتماشى مع أهداف عملك، من اختيار الجهاز إلى تكامل المنصة.',
    'iot.service2.title': 'إدارة أجهزة إنترنت الأشياء الآمنة',
    'iot.service2.desc': 'ضمان التوفير والمراقبة والتحديث الآمن لجميع أجهزتك المتصلة طوال دورة حياتها.',
    'iot.service3.title': 'تكامل السحابة وتحليلات البيانات',
    'iot.service3.desc': 'ربط أجهزة إنترنت الأشياء الخاصة بك بسلاسة بمنصات السحابة واستخلاص رؤى قابلة للتنفيذ من البيانات المجمعة.',
    'iot.service4.title': 'أمان وامتثال إنترنت الأشياء',
    'iot.service4.desc': 'تنفيذ بروتوكولات أمان متعددة الطبقات وضمان الامتثال لمعايير الصناعة لحماية النظام البيئي لإنترنت الأشياء الخاص بك.',
    'iot.service5.title': 'حلول الحوسبة الطرفية',
    'iot.service5.desc': 'معالجة البيانات بالقرب من المصدر لاتخاذ القرارات في الوقت الفعلي، وتقليل زمن الوصول، وتعزيز الأمان.',
    'iot.service6.title': 'إنترنت الأشياء الصناعي (IIoT)',
    'iot.service6.desc': 'تحسين التصنيع وسلسلة التوريد وإدارة الأصول مع تطبيقات IIoT القوية والآمنة.',
    
    // FAQ Page
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'اعثر على إجابات للأسئلة الشائعة حول خدمات IRONHEX',
    'faq.cat.general': 'معلومات عامة',
    'faq.cat.services': 'الخدمات والدعم',
    'faq.cat.technical': 'أسئلة تقنية',
    'faq.cat.billing': 'التسعير والفواتير',
    'faq.questions': 'سؤال',
    'faq.questions_plural': 'أسئلة',
    'faq.cta.title': 'لا تزال لديك أسئلة؟',
    'faq.cta.desc': 'فريقنا هنا للمساعدة. اتصل بنا للحصول على مساعدة شخصية.',
    'faq.cta.button': 'اتصل بنا',
    
    'faq.q1': 'ما هي الخدمات التي تقدمها IRONHEX؟',
    'faq.a1': 'تتخصص IRONHEX في حلول الأمن السيبراني الشاملة وخدمات إنترنت الأشياء. نقدم اختبار الاختراق، وتدقيق الأمان، وتقييم نقاط الضعف، وإدارة أجهزة إنترنت الأشياء، وحلول البرمجيات المخصصة لعملاء المؤسسات.',
    'faq.q2': 'كيف يمكنني البدء بخدمات IRONHEX؟',
    'faq.a2': 'البدء سهل! ما عليك سوى الاتصال بنا من خلال نموذج الاتصال أو البريد الإلكتروني أو الهاتف. سيقوم فريقنا بجدولة استشارة لفهم متطلباتك واقتراح أفضل حل لاحتياجاتك.',
    'faq.q3': 'هل تقدمون الدعم على مدار الساعة طوال أيام الأسبوع؟',
    'faq.a3': 'نعم، نقدم دعمًا على مدار الساعة طوال أيام الأسبوع لعملاء المؤسسات وعملاء الخدمات المُدارة. فريق الدعم لدينا متاح دائمًا لمعالجة الحوادث الأمنية الحرجة وتقديم المساعدة التقنية.',
    'faq.q4': 'ما هي الصناعات التي تخدمونها؟',
    'faq.a4': 'نخدم مجموعة واسعة من الصناعات بما في ذلك الخدمات المالية والرعاية الصحية والتصنيع والبيع بالتجزئة والوكالات الحكومية وشركات التكنولوجيا. حلولنا مصممة خصيصًا لتلبية متطلبات الامتثال والأمان الخاصة بالصناعة.',
    'faq.q5': 'كم من الوقت يستغرق تدقيق الأمان؟',
    'faq.a5': 'تعتمد مدة تدقيق الأمان على نطاق وتعقيد بنيتك التحتية. عادةً، يستغرق التدقيق الشامل من 2 إلى 4 أسابيع. نحن نقدم جدولًا زمنيًا مفصلاً أثناء الاستشارة الأولية.',
    'faq.q6': 'ما هو اختبار الاختراق؟',
    'faq.a6': 'اختبار الاختراق هو هجوم إلكتروني محاكى على نظامك لتحديد نقاط الضعف قبل أن يتمكن الجهات الفاعلة الخبيثة من استغلالها. يستخدم قراصنة أخلاقيون معتمدون لدينا منهجيات معيارية في الصناعة لاختبار وضعك الأمني.',
    'faq.q7': 'هل تقدمون خدمات التدريب؟',
    'faq.a7': 'نعم، نقدم تدريبًا على الوعي الأمني للموظفين، وتدريبًا تقنيًا لفرق تكنولوجيا المعلومات، ودورات تحضيرية متخصصة لشهادات الأمن السيبراني.',
    'faq.q8': 'ما هو نموذج التسعير الخاص بك؟',
    'faq.a8': 'نقدم نماذج تسعير مرنة بما في ذلك المشاريع والعقود الشهرية والحزم المخصصة. يعتمد التسعير على نطاق الخدمات والمدة والمتطلبات المحددة. اتصل بنا للحصول على عرض أسعار مفصل.',
    'faq.q9': 'هل حلولكم متوافقة مع اللوائح؟',
    'faq.a9': 'نعم، تم تصميم حلولنا لمساعدتك في تلبية متطلبات الامتثال المختلفة بما في ذلك اللائحة العامة لحماية البيانات، HIPAA، PCI-DSS، ISO 27001 واللوائح المحلية. يمكننا المساعدة في تدقيق الامتثال والتوثيق.',
    'faq.q10': 'هل يمكنكم المساعدة في الاستجابة للحوادث؟',
    'faq.a10': 'بالتأكيد. نقدم خدمات استجابة سريعة للحوادث لمساعدتك في احتواء واستقصاء والتعافي من الاختراقات الأمنية. يمكن إشراك فريقنا عند الطلب أو من خلال عقد للحصول على استجابة ذات أولوية.',
    'faq.q11': 'ما الذي يميز IRONHEX عن المنافسين؟',
    'faq.a11': 'تجمع IRONHEX بين الخبرة التقنية العميقة ونهج يركز على العميل. نقدم حلولًا مخصصة، ونحافظ على الشفافية طوال المشاركات، ونضمن نقل المعرفة لتمكين فريقك.',
    'faq.q12': 'هل تقدمون خدمات عن بُعد أو في الموقع؟',
    'faq.a12': 'نقدم خدمات عن بُعد وفي الموقع حسب متطلباتك. يمكن إجراء العديد من التقييمات عن بُعد، بينما قد يتطلب البعض الآخر حضورًا في الموقع لاختبار الأمن المادي أو البيئات الحساسة.',
    
    // Tunisian Regulations Page
    'reg.title': 'اللوائح التونسية للأمن السيبراني',
    'reg.subtitle': 'فهم الإطار القانوني التونسي للأمن السيبراني وحماية البيانات',
    'reg.alert.title': 'الامتثال التنظيمي',
    'reg.alert.desc': 'تضمن IRONHEX أن جميع الخدمات متوافقة مع قوانين الأمن السيبراني التونسية والمعايير الدولية.',
    
    'reg.section1.title': 'قانون حماية البيانات',
    'reg.section1.subtitle': 'القانون الأساسي رقم 2004-63 المتعلق بحماية البيانات الشخصية',
    'reg.section1.p1': 'ينشئ قانون حماية البيانات التونسي الإطار لجمع ومعالجة وتخزين البيانات الشخصية. يجب على المؤسسات الحصول على موافقة صريحة قبل معالجة المعلومات الشخصية وتنفيذ تدابير أمنية مناسبة لحماية البيانات.',
    'reg.section1.requirements': 'المتطلبات الرئيسية:',
    'reg.section1.req1': 'التسجيل لدى الهيئة الوطنية لحماية البيانات الشخصية (INPDP)',
    'reg.section1.req2': 'تنفيذ تدابير الأمان التقنية والتنظيمية',
    'reg.section1.req3': 'الإخطار بخرق البيانات في غضون 72 ساعة',
    'reg.section1.req4': 'حقوق موضوع البيانات بما في ذلك الوصول والتصحيح والحذف',
    
    'reg.section2.title': 'قانون الجرائم السيبرانية',
    'reg.section2.subtitle': 'القانون رقم 2004-5 المتعلق بأمن الكمبيوتر وحماية البيانات',
    'reg.section2.p1': 'يعالج هذا القانون الجرائم السيبرانية ويحدد العقوبات على الوصول غير المصرح به إلى أنظمة الكمبيوتر وسرقة البيانات والجرائم السيبرانية الأخرى. يوفر الأساس القانوني لمقاضاة مجرمي الإنترنت وحماية البنية التحتية للمعلومات الحيوية.',
    'reg.section2.offenses': 'الجرائم المشمولة:',
    'reg.section2.off1': 'الوصول غير المصرح به إلى أنظمة الكمبيوتر',
    'reg.section2.off2': 'سرقة البيانات والاحتيال',
    'reg.section2.off3': 'توزيع البرامج الضارة',
    'reg.section2.off4': 'التحرش السيبراني والتهديدات عبر الإنترنت',
    
    'reg.section3.title': 'تنظيم الاتصالات الإلكترونية',
    'reg.section3.subtitle': 'قانون الاتصالات ولوائح الهيئة الوطنية للاتصالات',
    'reg.section3.p1': 'تنظم الهيئة الوطنية للاتصالات في تونس (INTT) الاتصالات الإلكترونية وأمن الشبكات. يجب على مقدمي الخدمات الامتثال للمعايير التقنية ومتطلبات الأمان.',
    
    'reg.section4.title': 'كيف تضمن IRONHEX الامتثال',
    'reg.section4.p1': 'تعمل IRONHEX مع المؤسسات لضمان الامتثال الكامل للوائح الأمن السيبراني التونسية:',
    'reg.section4.service1.title': 'تدقيق الامتثال',
    'reg.section4.service1.desc': 'تقييمات شاملة لحالة الامتثال الحالية الخاصة بك مقابل اللوائح التونسية',
    'reg.section4.service2.title': 'تطوير السياسات',
    'reg.section4.service2.desc': 'إنشاء سياسات وإجراءات متوافقة مع المتطلبات القانونية',
    'reg.section4.service3.title': 'تنفيذ الأمان',
    'reg.section4.service3.desc': 'نشر الضوابط التقنية لتلبية معايير الأمان التنظيمية',
    'reg.section4.service4.title': 'المراقبة المستمرة',
    'reg.section4.service4.desc': 'مراقبة وإبلاغ الامتثال المستمر',
    
    'reg.disclaimer.title': 'إخلاء المسؤولية:',
    'reg.disclaimer.text': 'يتم توفير هذه المعلومات للإرشاد العام فقط ولا تشكل نصيحة قانونية. للأسئلة القانونية المحددة، يرجى استشارة محامٍ مؤهل.',
    
    'reg.cta.title': 'تحتاج مساعدة في الامتثال؟',
    'reg.cta.desc': 'اتصل بخبرائنا لضمان امتثال مؤسستك لجميع المتطلبات التنظيمية',
    'reg.cta.button': 'ابدأ الآن',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
