import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.cybersecurity': 'Cybersecurity',
    'nav.iot': 'IoT Solutions',
    'nav.software': 'Software Solutions',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.regulations': 'Tunisian Regulations',
    'nav.terms': 'Terms of Service',
    'nav.privacy': 'Privacy Policy',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'Providing robust cybersecurity and innovative IoT solutions to secure your digital future.',
    'footer.quickLinks': 'Quick Links',
    'footer.ourServices': 'Our Services',
    'footer.getInTouch': 'Get in Touch',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.address': 'Address',
    'footer.location': 'Megrine, Ben Arous',
    'footer.country': 'Tunisia',
    'footer.contactUs': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    
    // Home
    'home.hero.title': 'Strong Security for an Interconnected World',
    'home.hero.description': 'Protecting your business with advanced cybersecurity and intelligent IOT solutions',
    'home.hero.cta': 'Contact Us',
    'home.services.title': 'Our Core Services',
    'home.services.cyber.title': 'Cybersecurity Services',
    'home.services.cyber.desc': 'Proactive defense against evolving digital threats',
    'home.services.iot.title': 'IoT Services',
    'home.services.iot.desc': 'Secure and seamless integration of smart devices',
    'home.services.managed.title': 'Managed Security & Support',
    'home.services.managed.desc': '24/7 monitoring, rapid response, and expert guidance',
    'home.testimonials.title': 'What clients say',
    'home.testimonials.1': '"IRONHEX secured our IoT rollout and improved monitoring — their team is top notch."',
    'home.testimonials.1.author': '- CTO, Acme Corp',
    'home.testimonials.2': '"Response times and the expertise are exceptional. Recommended."',
    'home.testimonials.2.author': '- Head of IT, Beta Ltd',
    'home.partners.title': 'Our partners',
    
    // Contact Form
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    
    // Software Solutions
    'software.title': 'Ready-Made Website Solutions',
    'software.subtitle': 'Professional, fully-functional website platforms ready to deploy. Request a live demo to see them in action.',
    'software.features': 'Key Features:',
    'software.technologies': 'Technologies:',
    'software.requestDemo': 'Request Live Demo',
    'software.customTitle': 'Need a Custom Website Solution?',
    'software.customDesc': 'Our team can develop a tailored website platform specifically designed for your unique business requirements',
    'software.customCta': 'Contact Us for Custom Development',
    
    // Demo Request
    'demo.title': 'Request Demo',
    'demo.description': 'Fill in your details and we\'ll schedule a personalized demo session to showcase the platform\'s capabilities.',
    'demo.fullName': 'Full Name',
    'demo.email': 'Email Address',
    'demo.phone': 'Phone Number',
    'demo.company': 'Company Name (Optional)',
    'demo.message': 'Additional Information (Optional)',
    'demo.messagePlaceholder': 'Tell us about your requirements or specific features you\'re interested in...',
    'demo.selectedPlatform': 'Selected Platform:',
    'demo.cancel': 'Cancel',
    'demo.submit': 'Submit Demo Request',
    'demo.success': 'Demo Request Submitted!',
    'demo.successDesc': 'Our team will contact you within 24 hours to schedule a demo.',
    'demo.error': 'Error',
    'demo.errorDesc': 'Failed to submit demo request. Please try again.',
    
    // Common
    'common.loading': 'Loading...',
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.contactUs': 'Contact Us',
    
    // Services Page
    'services.title': 'Our Services',
    'services.subtitle': 'We specialise in Cybersecurity and IoT solutions tailored to your needs. Select a service area below to learn more.',
    'services.cyber.title': 'Cybersecurity Services',
    'services.cyber.desc': 'Proactive defenses, managed security, and compliance guidance.',
    'services.cyber.cta': 'Explore Cybersecurity',
    'services.iot.title': 'IoT Services',
    'services.iot.desc': 'Secure device integration, edge computing, and analytics.',
    'services.iot.cta': 'Explore IoT',
    
    // About Page
    'about.title': 'About IRONHEX',
    'about.subtitle': 'Secure Today, Save Tomorrow',
    'about.intro': 'Founded on expertise, driven by innovation, and committed to a secure digital future.',
    'about.story.title': 'Our Story: Born from Vision and Expertise',
    'about.story.p1': 'IRONHEX was founded in Tunisia in 2025 by two visionary female engineers, each bringing a unique and powerful skillset to the burgeoning fields of cybersecurity and the Internet of Things (IoT). Their shared passion for innovation and an unwavering commitment to digital security laid the groundwork for a company designed to protect and empower businesses in an increasingly connected world.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To provide cutting-edge cybersecurity and intelligent IoT solutions that empower businesses to thrive securely in a complex digital landscape, fostering innovation while ensuring data integrity and privacy.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the leading trusted partner in digital security and IoT innovation across Tunisia and beyond, shaping a future where technology is both powerful and inherently safe for everyone.',
    'about.founders.title': 'Meet Our Founders',
    'about.founder1.name': 'Imen Chihi',
    'about.founder1.role': 'Co-Founder & CISO',
    'about.founder1.desc': 'A brilliant mind in cybersecurity, Imen leads IRONHEX\'s defense strategies, ensuring our clients and their assets are protected against the most sophisticated digital threats. Her expertise spans threat intelligence, incident response, and secure architecture design.',
    'about.founder2.name': 'Arij Saleh',
    'about.founder2.role': 'Co-Founder & CTO',
    'about.founder2.desc': 'Arij is the driving force behind IRONHEX\'s innovative IoT solutions. With a deep understanding of connected ecosystems, she architects smart, efficient, and scalable IoT deployments that transform businesses and industries.',
    'about.journey.title': 'Join Our Journey',
    'about.journey.desc': 'We are always looking for passionate talent to join our growing team. Explore career opportunities or get in touch to learn more about how we can help secure your digital world.',
    'about.journey.cta': 'Contact Us',
    
    // Cybersecurity Page
    'cyber.hero.title': 'Fortify Your Digital Fortress',
    'cyber.hero.desc': 'IRONHEX provides comprehensive cybersecurity solutions to protect your business from evolving threats and ensure digital resilience.',
    'cyber.hero.offerings': 'Our Offerings',
    'cyber.hero.consultation': 'Get a Consultation',
    'cyber.intro.title': 'Proactive Defense in a Complex Digital Landscape',
    'cyber.intro.p1': 'In today\'s interconnected world, cybersecurity is not just a necessity; it\'s the foundation of business continuity and trust. IRONHEX offers a full spectrum of cybersecurity services designed to identify, protect, detect, respond, and recover from cyber threats.',
    'cyber.intro.p2': 'We combine cutting-edge technology with expert human intelligence to build multi-layered defenses that safeguard your data, systems, and reputation against sophisticated attacks.',
    'cyber.services.title': 'Our Cybersecurity Service Spectrum',
    'cyber.service1.title': 'Managed Security Services',
    'cyber.service1.desc': '24/7 monitoring, threat detection, and rapid response by our Security Operations Center (SOC) experts.',
    'cyber.service2.title': 'Vulnerability Management',
    'cyber.service2.desc': 'Regular scanning, penetration testing, and risk assessments to identify and mitigate security weaknesses.',
    'cyber.service3.title': 'Cloud Security',
    'cyber.service3.desc': 'Secure your cloud infrastructure (AWS, Azure, GCP), applications, and data with robust controls.',
    'cyber.service4.title': 'Endpoint Protection',
    'cyber.service4.desc': 'Advanced protection for all devices, from laptops to servers, against malware, ransomware, and zero-day threats.',
    'cyber.service5.title': 'Identity & Access Management (IAM)',
    'cyber.service5.desc': 'Control who accesses what, enforce multi-factor authentication, and manage user identities securely.',
    'cyber.service6.title': 'Compliance & Regulatory Support',
    'cyber.service6.desc': 'Navigate complex regulatory landscapes (GDPR, HIPAA, ISO 27001) with our expert guidance and solutions.',
    
    // IoT Page
    'iot.hero.title': 'Secure & Seamless IoT Integration',
    'iot.hero.desc': 'Unlock the full potential of your connected devices with IRONHEX\'s intelligent IoT solutions, designed for security and efficiency.',
    'iot.hero.features': 'Explore Features',
    'iot.hero.consultation': 'Get a Consultation',
    'iot.intro.title': 'Transform Your Business with Smart IoT',
    'iot.intro.p1': 'The Internet of Things (IoT) is revolutionizing industries by connecting physical devices to the internet, enabling them to collect and exchange data. At IRONHEX, we empower your business to harness this power through secure, scalable, and intelligent IoT solutions.',
    'iot.intro.p2': 'From smart infrastructure to industrial automation, our experts design, implement, and manage IoT ecosystems that drive efficiency, innovation, and growth while ensuring robust security from edge to cloud.',
    'iot.services.title': 'Our Comprehensive IoT Service Offerings',
    'iot.service1.title': 'IoT Strategy & Consulting',
    'iot.service1.desc': 'Develop a clear IoT roadmap aligned with your business objectives, from device selection to platform integration.',
    'iot.service2.title': 'Secure IoT Device Management',
    'iot.service2.desc': 'Ensure the secure provisioning, monitoring, and updating of all your connected devices throughout their lifecycle.',
    'iot.service3.title': 'Cloud Integration & Data Analytics',
    'iot.service3.desc': 'Seamlessly connect your IoT devices to cloud platforms and derive actionable insights from collected data.',
    'iot.service4.title': 'IoT Security & Compliance',
    'iot.service4.desc': 'Implement multi-layered security protocols and ensure compliance with industry standards to protect your IoT ecosystem.',
    'iot.service5.title': 'Edge Computing Solutions',
    'iot.service5.desc': 'Process data closer to the source for real-time decision-making, reduced latency, and enhanced security.',
    'iot.service6.title': 'Industrial IoT (IIoT)',
    'iot.service6.desc': 'Optimize manufacturing, supply chain, and asset management with robust and secure IIoT implementations.',
    
    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about IRONHEX services',
    'faq.cat.general': 'General Information',
    'faq.cat.services': 'Services & Support',
    'faq.cat.technical': 'Technical Questions',
    'faq.cat.billing': 'Pricing & Billing',
    'faq.questions': 'question',
    'faq.questions_plural': 'questions',
    'faq.cta.title': 'Still have questions?',
    'faq.cta.desc': 'Our team is here to help. Contact us for personalized assistance.',
    'faq.cta.button': 'Contact Us',
    
    'faq.q1': 'What services does IRONHEX provide?',
    'faq.a1': 'IRONHEX specializes in comprehensive cybersecurity solutions and IoT services. We offer penetration testing, security audits, vulnerability assessments, IoT device management, and custom software solutions for enterprise clients.',
    'faq.q2': 'How can I get started with IRONHEX services?',
    'faq.a2': 'Getting started is easy! Simply contact us through our contact form, email, or phone. Our team will schedule a consultation to understand your requirements and propose the best solution for your needs.',
    'faq.q3': 'Do you provide 24/7 support?',
    'faq.a3': 'Yes, we offer 24/7 support for our enterprise clients and managed service customers. Our support team is always available to address critical security incidents and provide technical assistance.',
    'faq.q4': 'What industries do you serve?',
    'faq.a4': 'We serve a wide range of industries including financial services, healthcare, manufacturing, retail, government agencies, and technology companies. Our solutions are tailored to meet industry-specific compliance and security requirements.',
    'faq.q5': 'How long does a security audit take?',
    'faq.a5': 'The duration of a security audit depends on the scope and complexity of your infrastructure. Typically, a comprehensive audit takes 2-4 weeks. We provide a detailed timeline during the initial consultation.',
    'faq.q6': 'What is penetration testing?',
    'faq.a6': 'Penetration testing is a simulated cyber attack on your system to identify vulnerabilities before malicious actors can exploit them. Our certified ethical hackers use industry-standard methodologies to test your security posture.',
    'faq.q7': 'Do you offer training services?',
    'faq.a7': 'Yes, we provide security awareness training for employees, technical training for IT teams, and specialized cybersecurity certification preparation courses.',
    'faq.q8': 'What is your pricing model?',
    'faq.a8': 'We offer flexible pricing models including project-based, monthly retainers, and custom packages. Pricing depends on the scope of services, duration, and specific requirements. Contact us for a detailed quote.',
    'faq.q9': 'Are your solutions compliant with regulations?',
    'faq.a9': 'Yes, our solutions are designed to help you meet various compliance requirements including GDPR, HIPAA, PCI-DSS, ISO 27001, and local regulations. We can assist with compliance audits and documentation.',
    'faq.q10': 'Can you help with incident response?',
    'faq.a10': 'Absolutely. We offer rapid incident response services to help you contain, investigate, and recover from security breaches. Our team can be engaged on-demand or through a retainer for priority response.',
    'faq.q11': 'What makes IRONHEX different from competitors?',
    'faq.a11': 'IRONHEX combines deep technical expertise with a customer-first approach. We provide tailored solutions, maintain transparency throughout engagements, and ensure knowledge transfer to empower your team.',
    'faq.q12': 'Do you provide remote or on-site services?',
    'faq.a12': 'We offer both remote and on-site services depending on your requirements. Many assessments can be conducted remotely, while others may require on-site presence for physical security testing or sensitive environments.',
    
    // Tunisian Regulations Page
    'reg.title': 'Tunisian Cybersecurity Regulations',
    'reg.subtitle': 'Understanding Tunisia\'s legal framework for cybersecurity and data protection',
    'reg.alert.title': 'Regulatory Compliance',
    'reg.alert.desc': 'IRONHEX ensures all services comply with Tunisian cybersecurity laws and international standards.',
    
    'reg.section1.title': 'Data Protection Law',
    'reg.section1.subtitle': 'Organic Law No. 2004-63 on the Protection of Personal Data',
    'reg.section1.p1': 'Tunisia\'s data protection law establishes the framework for collecting, processing, and storing personal data. Organizations must obtain explicit consent before processing personal information and implement appropriate security measures to protect data.',
    'reg.section1.requirements': 'Key Requirements:',
    'reg.section1.req1': 'Registration with the National Authority for Personal Data Protection (INPDP)',
    'reg.section1.req2': 'Implementation of technical and organizational security measures',
    'reg.section1.req3': 'Data breach notification within 72 hours',
    'reg.section1.req4': 'Data subject rights including access, rectification, and deletion',
    
    'reg.section2.title': 'Cybercrime Law',
    'reg.section2.subtitle': 'Law No. 2004-5 on Computer Security and Data Protection',
    'reg.section2.p1': 'This law addresses cybercrime and establishes penalties for unauthorized access to computer systems, data theft, and other cyber offenses. It provides the legal foundation for prosecuting cybercriminals and protecting critical information infrastructure.',
    'reg.section2.offenses': 'Covered Offenses:',
    'reg.section2.off1': 'Unauthorized access to computer systems',
    'reg.section2.off2': 'Data theft and fraud',
    'reg.section2.off3': 'Distribution of malware',
    'reg.section2.off4': 'Cyber harassment and online threats',
    
    'reg.section3.title': 'Electronic Communications Regulation',
    'reg.section3.subtitle': 'Telecommunications Code and INTT Regulations',
    'reg.section3.p1': 'The National Telecommunications Institute of Tunisia (INTT) regulates electronic communications and network security. Service providers must comply with technical standards and security requirements.',
    
    'reg.section4.title': 'How IRONHEX Ensures Compliance',
    'reg.section4.p1': 'IRONHEX works with organizations to ensure full compliance with Tunisian cybersecurity regulations:',
    'reg.section4.service1.title': 'Compliance Audits',
    'reg.section4.service1.desc': 'Comprehensive assessments of your current compliance status against Tunisian regulations',
    'reg.section4.service2.title': 'Policy Development',
    'reg.section4.service2.desc': 'Creation of policies and procedures aligned with legal requirements',
    'reg.section4.service3.title': 'Security Implementation',
    'reg.section4.service3.desc': 'Deployment of technical controls to meet regulatory security standards',
    'reg.section4.service4.title': 'Ongoing Monitoring',
    'reg.section4.service4.desc': 'Continuous compliance monitoring and reporting',
    
    'reg.disclaimer.title': 'Disclaimer:',
    'reg.disclaimer.text': 'This information is provided for general guidance only and does not constitute legal advice. For specific legal questions, please consult with a qualified legal professional.',
    
    'reg.cta.title': 'Need Help with Compliance?',
    'reg.cta.desc': 'Contact our experts to ensure your organization meets all regulatory requirements',
    'reg.cta.button': 'Get Started',

    // Terms of Service
    'terms.title': 'Terms of Service',
    'terms.lastUpdated': 'Last Updated: October 31, 2025',
    'terms.intro': 'Welcome to IRONHEX. By accessing or using our services, you agree to be bound by these Terms of Service. Please read them carefully.',
    
    'terms.acceptance.title': '1. Acceptance of Terms',
    'terms.acceptance.content': 'By accessing and using IRONHEX services, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services.',
    
    'terms.services.title': '2. Description of Services',
    'terms.services.content': 'IRONHEX provides cybersecurity solutions, IoT integration services, and software development services to businesses and organizations. Our services include but are not limited to security assessments, penetration testing, security monitoring, IoT device management, and custom software development.',
    
    'terms.responsibilities.title': '3. User Responsibilities',
    'terms.responsibilities.intro': 'When using our services, you agree to:',
    'terms.responsibilities.1': 'Provide accurate and complete information',
    'terms.responsibilities.2': 'Maintain the confidentiality of your account credentials',
    'terms.responsibilities.3': 'Use our services only for lawful purposes',
    'terms.responsibilities.4': 'Not interfere with or disrupt our services',
    'terms.responsibilities.5': 'Not attempt unauthorized access to our systems',
    'terms.responsibilities.6': 'Comply with all applicable laws and regulations',
    'terms.responsibilities.7': 'Notify us immediately of any security breaches',
    
    'terms.ip.title': '4. Intellectual Property',
    'terms.ip.content': 'All content, features, and functionality of IRONHEX services, including but not limited to text, graphics, logos, software, and documentation, are the exclusive property of IRONHEX and are protected by international copyright, trademark, and other intellectual property laws.',
    
    'terms.availability.title': '5. Service Availability',
    'terms.availability.content': 'While we strive to provide reliable services, we do not guarantee that our services will be uninterrupted, timely, secure, or error-free. We reserve the right to modify, suspend, or discontinue any part of our services at any time without notice.',
    
    'terms.confidentiality.title': '6. Confidentiality',
    'terms.confidentiality.intro': 'We take the confidentiality of your information seriously and commit to:',
    'terms.confidentiality.1': 'Protecting your confidential information with industry-standard security measures',
    'terms.confidentiality.2': 'Not disclosing your information to third parties without your consent',
    'terms.confidentiality.3': 'Using your information only for providing and improving our services',
    'terms.confidentiality.4': 'Maintaining appropriate technical and organizational security measures',
    
    'terms.liability.title': '7. Limitation of Liability',
    'terms.liability.content': 'To the maximum extent permitted by law, IRONHEX shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of our services.',
    
    'terms.indemnification.title': '8. Indemnification',
    'terms.indemnification.intro': 'You agree to indemnify, defend, and hold harmless IRONHEX and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses arising out of or in any way connected with:',
    'terms.indemnification.1': 'Your access to or use of our services',
    'terms.indemnification.2': 'Your violation of these Terms of Service',
    'terms.indemnification.3': 'Your violation of any third-party rights',
    'terms.indemnification.4': 'Any unauthorized use of our services',
    
    'terms.governing.title': '9. Governing Law',
    'terms.governing.content': 'These Terms of Service shall be governed by and construed in accordance with the laws of Tunisia. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of Tunisia.',
    
    'terms.payment.title': '10. Payment Terms',
    'terms.payment.content': 'Payment terms for our services will be specified in individual service agreements. All fees are non-refundable unless otherwise stated in writing. Late payments may result in service suspension.',
    
    'terms.termination.title': '11. Termination',
    'terms.termination.content': 'We reserve the right to terminate or suspend your access to our services at any time, without prior notice, for conduct that we believe violates these Terms of Service or is harmful to other users, us, or third parties, or for any other reason.',
    
    'terms.changes.title': '12. Changes to Terms',
    'terms.changes.content': 'We reserve the right to modify these Terms of Service at any time. We will notify users of any material changes by posting the new terms on our website. Your continued use of our services after such changes constitutes acceptance of the new terms.',
    
    'terms.contact.title': '13. Contact Information',
    'terms.contact.content': 'If you have any questions about these Terms of Service, please contact us at:',
    'terms.contact.email': 'Email: contact@ironhex-tech.com',
    'terms.contact.phone': 'Phone: +216 70 123 456',
    'terms.contact.address': 'Address: Megrine, Tunisia',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated: October 31, 2025',
    'privacy.intro': 'At IRONHEX, we are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information.',
    
    'privacy.collection.title': '1. Information We Collect',
    'privacy.collection.personal.title': 'Personal Information',
    'privacy.collection.personal.content': 'We collect information that you provide directly to us, including name, email address, phone number, company name, job title, and any other information you choose to provide when contacting us or using our services.',
    'privacy.collection.automatic.title': 'Automatically Collected Information',
    'privacy.collection.automatic.content': 'When you visit our website, we automatically collect certain information about your device, including IP address, browser type, operating system, referring URLs, and pages visited.',
    'privacy.collection.technical.title': 'Technical Information',
    'privacy.collection.technical.content': 'During service provision, we may collect technical information necessary to provide cybersecurity and IoT services, including network configurations, device information, and security logs.',
    
    'privacy.usage.title': '2. How We Use Your Information',
    'privacy.usage.intro': 'We use the information we collect to:',
    'privacy.usage.1': 'Provide, maintain, and improve our services',
    'privacy.usage.2': 'Respond to your inquiries and provide customer support',
    'privacy.usage.3': 'Send you technical notices and security alerts',
    'privacy.usage.4': 'Communicate about products, services, and events',
    'privacy.usage.5': 'Analyze usage patterns and improve user experience',
    'privacy.usage.6': 'Detect, prevent, and address security issues',
    'privacy.usage.7': 'Comply with legal obligations',
    
    'privacy.sharing.title': '3. Information Sharing',
    'privacy.sharing.intro': 'We do not sell your personal information. We may share your information only in the following circumstances:',
    'privacy.sharing.1': 'With your explicit consent',
    'privacy.sharing.2': 'With service providers who assist in our operations',
    'privacy.sharing.3': 'To comply with legal obligations',
    'privacy.sharing.4': 'To protect our rights and safety',
    'privacy.sharing.5': 'In connection with a business transfer or acquisition',
    
    'privacy.security.title': '4. Data Security',
    'privacy.security.intro': 'We implement appropriate technical and organizational measures to protect your information:',
    'privacy.security.1': 'Encryption of data in transit and at rest',
    'privacy.security.2': 'Regular security assessments and audits',
    'privacy.security.3': 'Access controls and authentication mechanisms',
    'privacy.security.4': 'Employee training on data protection',
    'privacy.security.5': 'Incident response procedures',
    'privacy.security.6': 'Regular backups and disaster recovery plans',
    
    'privacy.retention.title': '5. Data Retention',
    'privacy.retention.content': 'We retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law. When we no longer need your information, we securely delete or anonymize it.',
    
    'privacy.rights.title': '6. Your Rights',
    'privacy.rights.intro': 'You have the following rights regarding your personal information:',
    'privacy.rights.1': 'Access: Request access to your personal information',
    'privacy.rights.2': 'Correction: Request correction of inaccurate information',
    'privacy.rights.3': 'Deletion: Request deletion of your information',
    'privacy.rights.4': 'Portability: Request a copy of your data in a portable format',
    'privacy.rights.5': 'Restriction: Request restriction of processing',
    'privacy.rights.6': 'Objection: Object to processing of your information',
    'privacy.rights.7': 'Withdraw Consent: Withdraw consent at any time',
    'privacy.rights.8': 'Opt-Out: Opt-out of marketing communications',
    
    'privacy.cookies.title': '7. Cookies and Tracking',
    'privacy.cookies.content': 'We use cookies and similar tracking technologies to collect information about your browsing activities. You can control cookies through your browser settings. Note that disabling cookies may affect the functionality of our website.',
    
    'privacy.thirdparty.title': '8. Third-Party Links',
    'privacy.thirdparty.content': 'Our website may contain links to third-party websites. We are not responsible for the privacy practices of these websites. We encourage you to read their privacy policies.',
    
    'privacy.children.title': '9. Children\'s Privacy',
    'privacy.children.content': 'Our services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If we learn that we have collected information from a child, we will delete it promptly.',
    
    'privacy.international.title': '10. International Data Transfers',
    'privacy.international.content': 'Your information may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place to protect your information in accordance with this Privacy Policy.',
    
    'privacy.gdpr.title': '11. GDPR Compliance',
    'privacy.gdpr.content': 'For users in the European Economic Area (EEA), we comply with the General Data Protection Regulation (GDPR). We process your personal data based on legal grounds including consent, contract performance, legal obligations, and legitimate interests.',
    
    'privacy.changes.title': '12. Changes to Privacy Policy',
    'privacy.changes.content': 'We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on our website and updating the "Last Updated" date. Your continued use of our services after changes constitutes acceptance of the updated policy.',
    
    'privacy.contact.title': '13. Contact Us',
    'privacy.contact.content': 'If you have any questions about this Privacy Policy or our privacy practices, please contact us at:',
    'privacy.contact.dpo': 'Data Protection Officer',
    'privacy.contact.email': 'Email: contact@ironhex-tech.com',
    'privacy.contact.phone': 'Phone: +216 70 123 456',
    'privacy.contact.address': 'Address: Megrine, Tunisia',
  },
  fr: {
    // Navbar
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.services': 'Services',
    'nav.cybersecurity': 'Cybersécurité',
    'nav.iot': 'Solutions IoT',
    'nav.software': 'Solutions Logicielles',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.regulations': 'Réglementations Tunisiennes',
    'nav.terms': 'Conditions d\'Utilisation',
    'nav.privacy': 'Politique de Confidentialité',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'Fournir des solutions robustes de cybersécurité et IoT innovantes pour sécuriser votre avenir numérique.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.ourServices': 'Nos Services',
    'footer.getInTouch': 'Contactez-nous',
    'footer.email': 'Email',
    'footer.phone': 'Téléphone',
    'footer.address': 'Adresse',
    'footer.location': 'Mégrine, Ben Arous',
    'footer.country': 'Tunisie',
    'footer.contactUs': 'Nous Contacter',
    'footer.rights': 'Tous droits réservés.',
    
    // Home
    'home.hero.title': 'Sécurité Inébranlable pour un Monde Interconnecté',
    'home.hero.description': 'Protéger votre entreprise avec une cybersécurité avancée et des solutions IoT intelligentes',
    'home.hero.cta': 'Obtenir une Évaluation de Sécurité Gratuite',
    'home.services.title': 'Nos Services Principaux',
    'home.services.cyber.title': 'Services de Cybersécurité',
    'home.services.cyber.desc': 'Défense proactive contre les menaces numériques évolutives',
    'home.services.iot.title': 'Services IoT',
    'home.services.iot.desc': 'Intégration sécurisée et transparente des appareils intelligents',
    'home.services.managed.title': 'Sécurité Gérée & Support',
    'home.services.managed.desc': 'Surveillance 24/7, réponse rapide et conseils d\'experts',
    'home.testimonials.title': 'Ce que disent les clients',
    'home.testimonials.1': '"IRONHEX a sécurisé notre déploiement IoT et amélioré la surveillance - leur équipe est de premier ordre."',
    'home.testimonials.1.author': '- CTO, Acme Corp',
    'home.testimonials.2': '"Les temps de réponse et l\'expertise sont exceptionnels. Recommandé."',
    'home.testimonials.2.author': '- Responsable IT, Beta Ltd',
    'home.partners.title': 'Nos partenaires',
    
    // Contact Form
    'contact.name': 'Nom',
    'contact.email': 'Email',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'contact.sending': 'Envoi...',
    
    // Software Solutions
    'software.title': 'Solutions Web Prêtes à l\'Emploi',
    'software.subtitle': 'Plateformes web professionnelles et entièrement fonctionnelles prêtes à déployer. Demandez une démo en direct.',
    'software.features': 'Fonctionnalités Clés:',
    'software.technologies': 'Technologies:',
    'software.requestDemo': 'Demander une Démo',
    'software.customTitle': 'Besoin d\'une Solution Web Personnalisée?',
    'software.customDesc': 'Notre équipe peut développer une plateforme web sur mesure spécialement conçue pour vos besoins uniques',
    'software.customCta': 'Contactez-nous pour un Développement Personnalisé',
    
    // Demo Request
    'demo.title': 'Demander une Démo',
    'demo.description': 'Remplissez vos coordonnées et nous planifierons une session de démonstration personnalisée.',
    'demo.fullName': 'Nom Complet',
    'demo.email': 'Adresse Email',
    'demo.phone': 'Numéro de Téléphone',
    'demo.company': 'Nom de l\'Entreprise (Optionnel)',
    'demo.message': 'Informations Supplémentaires (Optionnel)',
    'demo.messagePlaceholder': 'Parlez-nous de vos besoins ou des fonctionnalités spécifiques qui vous intéressent...',
    'demo.selectedPlatform': 'Plateforme Sélectionnée:',
    'demo.cancel': 'Annuler',
    'demo.submit': 'Soumettre la Demande',
    'demo.success': 'Demande de Démo Soumise!',
    'demo.successDesc': 'Notre équipe vous contactera dans les 24 heures pour planifier une démo.',
    'demo.error': 'Erreur',
    'demo.errorDesc': 'Échec de la soumission de la demande de démo. Veuillez réessayer.',
    
    // Common
    'common.loading': 'Chargement...',
    'common.readMore': 'Lire Plus',
    'common.learnMore': 'En Savoir Plus',
    'common.getStarted': 'Commencer',
    'common.contactUs': 'Nous Contacter',
    
    // Services Page
    'services.title': 'Nos Services',
    'services.subtitle': 'Nous sommes spécialisés dans les solutions de cybersécurité et IoT adaptées à vos besoins. Sélectionnez un domaine de service ci-dessous pour en savoir plus.',
    'services.cyber.title': 'Services de Cybersécurité',
    'services.cyber.desc': 'Défenses proactives, sécurité gérée et conseils en conformité.',
    'services.cyber.cta': 'Explorer la Cybersécurité',
    'services.iot.title': 'Services IoT',
    'services.iot.desc': 'Intégration sécurisée des appareils, edge computing et analytique.',
    'services.iot.cta': 'Explorer l\'IoT',
    
    // About Page
    'about.title': 'À Propos d\'IRONHEX',
    'about.subtitle': 'Sécuriser Demain, Aujourd\'hui',
    'about.intro': 'Fondé sur l\'expertise, porté par l\'innovation et engagé pour un avenir numérique sécurisé.',
    'about.story.title': 'Notre Histoire: Née de la Vision et de l\'Expertise',
    'about.story.p1': 'IRONHEX a été fondée en Tunisie en 2025 par deux ingénieures visionnaires, chacune apportant un ensemble de compétences unique et puissant aux domaines émergents de la cybersécurité et de l\'Internet des Objets (IoT). Leur passion commune pour l\'innovation et leur engagement indéfectible envers la sécurité numérique ont jeté les bases d\'une entreprise conçue pour protéger et autonomiser les entreprises dans un monde de plus en plus connecté.',
    'about.mission.title': 'Notre Mission',
    'about.mission.desc': 'Fournir des solutions de cybersécurité de pointe et des solutions IoT intelligentes qui permettent aux entreprises de prospérer en toute sécurité dans un paysage numérique complexe, favorisant l\'innovation tout en garantissant l\'intégrité et la confidentialité des données.',
    'about.vision.title': 'Notre Vision',
    'about.vision.desc': 'Être le partenaire de confiance leader en sécurité numérique et innovation IoT en Tunisie et au-delà, façonnant un avenir où la technologie est à la fois puissante et intrinsèquement sûre pour tous.',
    'about.founders.title': 'Rencontrez Nos Fondatrices',
    'about.founder1.name': 'Imen Chihi',
    'about.founder1.role': 'Co-Fondatrice & CISO',
    'about.founder1.desc': 'Un esprit brillant en cybersécurité, Imen dirige les stratégies de défense d\'IRONHEX, garantissant que nos clients et leurs actifs sont protégés contre les menaces numériques les plus sophistiquées. Son expertise couvre le renseignement sur les menaces, la réponse aux incidents et la conception d\'architecture sécurisée.',
    'about.founder2.name': 'Arij Saleh',
    'about.founder2.role': 'Co-Fondatrice & CTO',
    'about.founder2.desc': 'Arij est la force motrice derrière les solutions IoT innovantes d\'IRONHEX. Avec une compréhension approfondie des écosystèmes connectés, elle conçoit des déploiements IoT intelligents, efficaces et évolutifs qui transforment les entreprises et les industries.',
    'about.journey.title': 'Rejoignez Notre Aventure',
    'about.journey.desc': 'Nous sommes toujours à la recherche de talents passionnés pour rejoindre notre équipe en pleine croissance. Explorez les opportunités de carrière ou contactez-nous pour en savoir plus sur la façon dont nous pouvons sécuriser votre monde numérique.',
    'about.journey.cta': 'Nous Contacter',
    
    // Cybersecurity Page
    'cyber.hero.title': 'Fortifiez Votre Forteresse Numérique',
    'cyber.hero.desc': 'IRONHEX fournit des solutions de cybersécurité complètes pour protéger votre entreprise contre les menaces évolutives et garantir la résilience numérique.',
    'cyber.hero.offerings': 'Nos Offres',
    'cyber.hero.consultation': 'Obtenir une Consultation',
    'cyber.intro.title': 'Défense Proactive dans un Paysage Numérique Complexe',
    'cyber.intro.p1': 'Dans le monde interconnecté d\'aujourd\'hui, la cybersécurité n\'est pas seulement une nécessité; c\'est le fondement de la continuité des activités et de la confiance. IRONHEX offre un spectre complet de services de cybersécurité conçus pour identifier, protéger, détecter, répondre et récupérer des menaces cybernétiques.',
    'cyber.intro.p2': 'Nous combinons une technologie de pointe avec l\'intelligence humaine experte pour construire des défenses multicouches qui protègent vos données, systèmes et réputation contre les attaques sophistiquées.',
    'cyber.services.title': 'Notre Spectre de Services de Cybersécurité',
    'cyber.service1.title': 'Services de Sécurité Gérés',
    'cyber.service1.desc': 'Surveillance 24/7, détection des menaces et réponse rapide par nos experts du Centre d\'Opérations de Sécurité (SOC).',
    'cyber.service2.title': 'Gestion des Vulnérabilités',
    'cyber.service2.desc': 'Analyse régulière, tests de pénétration et évaluations des risques pour identifier et atténuer les faiblesses de sécurité.',
    'cyber.service3.title': 'Sécurité Cloud',
    'cyber.service3.desc': 'Sécurisez votre infrastructure cloud (AWS, Azure, GCP), applications et données avec des contrôles robustes.',
    'cyber.service4.title': 'Protection des Points de Terminaison',
    'cyber.service4.desc': 'Protection avancée pour tous les appareils, des ordinateurs portables aux serveurs, contre les logiciels malveillants, ransomwares et menaces zero-day.',
    'cyber.service5.title': 'Gestion des Identités et des Accès (IAM)',
    'cyber.service5.desc': 'Contrôlez qui accède à quoi, appliquez l\'authentification multifacteur et gérez les identités des utilisateurs en toute sécurité.',
    'cyber.service6.title': 'Support Conformité & Réglementaire',
    'cyber.service6.desc': 'Naviguez dans les paysages réglementaires complexes (RGPD, HIPAA, ISO 27001) avec nos conseils et solutions d\'experts.',
    
    // IoT Page
    'iot.hero.title': 'Intégration IoT Sécurisée et Transparente',
    'iot.hero.desc': 'Libérez tout le potentiel de vos appareils connectés avec les solutions IoT intelligentes d\'IRONHEX, conçues pour la sécurité et l\'efficacité.',
    'iot.hero.features': 'Explorer les Fonctionnalités',
    'iot.hero.consultation': 'Obtenir une Consultation',
    'iot.intro.title': 'Transformez Votre Entreprise avec l\'IoT Intelligent',
    'iot.intro.p1': 'L\'Internet des Objets (IoT) révolutionne les industries en connectant les appareils physiques à Internet, leur permettant de collecter et d\'échanger des données. Chez IRONHEX, nous permettons à votre entreprise d\'exploiter ce pouvoir grâce à des solutions IoT sécurisées, évolutives et intelligentes.',
    'iot.intro.p2': 'De l\'infrastructure intelligente à l\'automatisation industrielle, nos experts conçoivent, mettent en œuvre et gèrent des écosystèmes IoT qui favorisent l\'efficacité, l\'innovation et la croissance tout en garantissant une sécurité robuste de la périphérie au cloud.',
    'iot.services.title': 'Nos Offres Complètes de Services IoT',
    'iot.service1.title': 'Stratégie et Conseil IoT',
    'iot.service1.desc': 'Développez une feuille de route IoT claire alignée sur vos objectifs commerciaux, de la sélection des appareils à l\'intégration de la plateforme.',
    'iot.service2.title': 'Gestion Sécurisée des Appareils IoT',
    'iot.service2.desc': 'Assurez le provisionnement, la surveillance et la mise à jour sécurisés de tous vos appareils connectés tout au long de leur cycle de vie.',
    'iot.service3.title': 'Intégration Cloud et Analytique de Données',
    'iot.service3.desc': 'Connectez de manière transparente vos appareils IoT aux plateformes cloud et tirez des informations exploitables des données collectées.',
    'iot.service4.title': 'Sécurité et Conformité IoT',
    'iot.service4.desc': 'Mettez en œuvre des protocoles de sécurité multicouches et assurez la conformité aux normes de l\'industrie pour protéger votre écosystème IoT.',
    'iot.service5.title': 'Solutions d\'Edge Computing',
    'iot.service5.desc': 'Traitez les données plus près de la source pour une prise de décision en temps réel, une latence réduite et une sécurité améliorée.',
    'iot.service6.title': 'IoT Industriel (IIoT)',
    'iot.service6.desc': 'Optimisez la fabrication, la chaîne d\'approvisionnement et la gestion des actifs avec des implémentations IIoT robustes et sécurisées.',
    
    // FAQ Page
    'faq.title': 'Foire Aux Questions',
    'faq.subtitle': 'Trouvez des réponses aux questions courantes sur les services IRONHEX',
    'faq.cat.general': 'Informations Générales',
    'faq.cat.services': 'Services & Support',
    'faq.cat.technical': 'Questions Techniques',
    'faq.cat.billing': 'Tarification & Facturation',
    'faq.questions': 'question',
    'faq.questions_plural': 'questions',
    'faq.cta.title': 'Vous avez encore des questions?',
    'faq.cta.desc': 'Notre équipe est là pour vous aider. Contactez-nous pour une assistance personnalisée.',
    'faq.cta.button': 'Nous Contacter',
    
    'faq.q1': 'Quels services IRONHEX propose-t-il?',
    'faq.a1': 'IRONHEX est spécialisé dans les solutions complètes de cybersécurité et les services IoT. Nous proposons des tests de pénétration, des audits de sécurité, des évaluations de vulnérabilité, la gestion d\'appareils IoT et des solutions logicielles personnalisées pour les clients d\'entreprise.',
    'faq.q2': 'Comment puis-je commencer avec les services IRONHEX?',
    'faq.a2': 'C\'est facile de commencer! Contactez-nous simplement via notre formulaire de contact, par e-mail ou par téléphone. Notre équipe planifiera une consultation pour comprendre vos besoins et proposer la meilleure solution.',
    'faq.q3': 'Offrez-vous un support 24h/24 et 7j/7?',
    'faq.a3': 'Oui, nous offrons un support 24h/24 et 7j/7 à nos clients d\'entreprise et aux clients de services gérés. Notre équipe d\'assistance est toujours disponible pour traiter les incidents de sécurité critiques et fournir une assistance technique.',
    'faq.q4': 'Quels secteurs servez-vous?',
    'faq.a4': 'Nous servons un large éventail de secteurs, notamment les services financiers, la santé, la fabrication, le commerce de détail, les agences gouvernementales et les entreprises technologiques. Nos solutions sont adaptées pour répondre aux exigences de conformité et de sécurité spécifiques à l\'industrie.',
    'faq.q5': 'Combien de temps dure un audit de sécurité?',
    'faq.a5': 'La durée d\'un audit de sécurité dépend de la portée et de la complexité de votre infrastructure. Généralement, un audit complet prend 2 à 4 semaines. Nous fournissons un calendrier détaillé lors de la consultation initiale.',
    'faq.q6': 'Qu\'est-ce qu\'un test de pénétration?',
    'faq.a6': 'Le test de pénétration est une attaque cybernétique simulée sur votre système pour identifier les vulnérabilités avant que des acteurs malveillants ne puissent les exploiter. Nos hackers éthiques certifiés utilisent des méthodologies standard de l\'industrie pour tester votre posture de sécurité.',
    'faq.q7': 'Offrez-vous des services de formation?',
    'faq.a7': 'Oui, nous proposons des formations de sensibilisation à la sécurité pour les employés, des formations techniques pour les équipes informatiques et des cours de préparation aux certifications spécialisées en cybersécurité.',
    'faq.q8': 'Quel est votre modèle de tarification?',
    'faq.a8': 'Nous proposons des modèles de tarification flexibles, y compris basés sur des projets, des contrats mensuels et des forfaits personnalisés. La tarification dépend de la portée des services, de la durée et des exigences spécifiques. Contactez-nous pour un devis détaillé.',
    'faq.q9': 'Vos solutions sont-elles conformes aux réglementations?',
    'faq.a9': 'Oui, nos solutions sont conçues pour vous aider à répondre à diverses exigences de conformité, notamment le RGPD, HIPAA, PCI-DSS, ISO 27001 et les réglementations locales. Nous pouvons vous aider avec les audits de conformité et la documentation.',
    'faq.q10': 'Pouvez-vous aider en cas d\'incident?',
    'faq.a10': 'Absolument. Nous offrons des services de réponse rapide aux incidents pour vous aider à contenir, enquêter et récupérer des violations de sécurité. Notre équipe peut être engagée à la demande ou via un contrat pour une réponse prioritaire.',
    'faq.q11': 'Qu\'est-ce qui distingue IRONHEX de ses concurrents?',
    'faq.a11': 'IRONHEX combine une expertise technique approfondie avec une approche centrée sur le client. Nous fournissons des solutions sur mesure, maintenons la transparence tout au long des engagements et assurons le transfert de connaissances pour autonomiser votre équipe.',
    'faq.q12': 'Fournissez-vous des services à distance ou sur site?',
    'faq.a12': 'Nous offrons des services à distance et sur site en fonction de vos besoins. De nombreuses évaluations peuvent être effectuées à distance, tandis que d\'autres peuvent nécessiter une présence sur site pour des tests de sécurité physique ou des environnements sensibles.',
    
    // Tunisian Regulations Page
    'reg.title': 'Réglementations Tunisiennes en Cybersécurité',
    'reg.subtitle': 'Comprendre le cadre juridique tunisien pour la cybersécurité et la protection des données',
    'reg.alert.title': 'Conformité Réglementaire',
    'reg.alert.desc': 'IRONHEX garantit que tous les services sont conformes aux lois tunisiennes sur la cybersécurité et aux normes internationales.',
    
    'reg.section1.title': 'Loi sur la Protection des Données',
    'reg.section1.subtitle': 'Loi Organique n° 2004-63 sur la Protection des Données Personnelles',
    'reg.section1.p1': 'La loi tunisienne sur la protection des données établit le cadre pour la collecte, le traitement et le stockage des données personnelles. Les organisations doivent obtenir un consentement explicite avant de traiter des informations personnelles et mettre en œuvre des mesures de sécurité appropriées pour protéger les données.',
    'reg.section1.requirements': 'Exigences Clés:',
    'reg.section1.req1': 'Enregistrement auprès de l\'Instance Nationale de Protection des Données Personnelles (INPDP)',
    'reg.section1.req2': 'Mise en œuvre de mesures de sécurité techniques et organisationnelles',
    'reg.section1.req3': 'Notification de violation de données dans les 72 heures',
    'reg.section1.req4': 'Droits des personnes concernées incluant l\'accès, la rectification et la suppression',
    
    'reg.section2.title': 'Loi sur la Cybercriminalité',
    'reg.section2.subtitle': 'Loi n° 2004-5 sur la Sécurité Informatique et la Protection des Données',
    'reg.section2.p1': 'Cette loi traite de la cybercriminalité et établit des sanctions pour l\'accès non autorisé aux systèmes informatiques, le vol de données et d\'autres infractions cybernétiques. Elle fournit la base juridique pour poursuivre les cybercriminels et protéger les infrastructures d\'information critiques.',
    'reg.section2.offenses': 'Infractions Couvertes:',
    'reg.section2.off1': 'Accès non autorisé aux systèmes informatiques',
    'reg.section2.off2': 'Vol de données et fraude',
    'reg.section2.off3': 'Distribution de logiciels malveillants',
    'reg.section2.off4': 'Harcèlement cybernétique et menaces en ligne',
    
    'reg.section3.title': 'Réglementation des Communications Électroniques',
    'reg.section3.subtitle': 'Code des Télécommunications et Règlements de l\'INTT',
    'reg.section3.p1': 'L\'Instance Nationale des Télécommunications de Tunisie (INTT) réglemente les communications électroniques et la sécurité des réseaux. Les fournisseurs de services doivent se conformer aux normes techniques et aux exigences de sécurité.',
    
    'reg.section4.title': 'Comment IRONHEX Assure la Conformité',
    'reg.section4.p1': 'IRONHEX travaille avec les organisations pour garantir une conformité totale avec les réglementations tunisiennes en cybersécurité:',
    'reg.section4.service1.title': 'Audits de Conformité',
    'reg.section4.service1.desc': 'Évaluations complètes de votre statut de conformité actuel par rapport aux réglementations tunisiennes',
    'reg.section4.service2.title': 'Développement de Politiques',
    'reg.section4.service2.desc': 'Création de politiques et de procédures alignées sur les exigences légales',
    'reg.section4.service3.title': 'Mise en Œuvre de la Sécurité',
    'reg.section4.service3.desc': 'Déploiement de contrôles techniques pour répondre aux normes de sécurité réglementaires',
    'reg.section4.service4.title': 'Surveillance Continue',
    'reg.section4.service4.desc': 'Surveillance et reporting continus de la conformité',
    
    'reg.disclaimer.title': 'Avertissement:',
    'reg.disclaimer.text': 'Ces informations sont fournies à titre indicatif uniquement et ne constituent pas un conseil juridique. Pour des questions juridiques spécifiques, veuillez consulter un professionnel juridique qualifié.',
    
    'reg.cta.title': 'Besoin d\'Aide pour la Conformité?',
    'reg.cta.desc': 'Contactez nos experts pour vous assurer que votre organisation respecte toutes les exigences réglementaires',
    'reg.cta.button': 'Commencer',

    // Terms of Service
    'terms.title': 'Conditions d\'Utilisation',
    'terms.lastUpdated': 'Dernière mise à jour : 31 octobre 2025',
    'terms.intro': 'Bienvenue chez IRONHEX. En accédant ou en utilisant nos services, vous acceptez d\'être lié par ces Conditions d\'Utilisation. Veuillez les lire attentivement.',
    
    'terms.acceptance.title': '1. Acceptation des Conditions',
    'terms.acceptance.content': 'En accédant et en utilisant les services IRONHEX, vous reconnaissez avoir lu, compris et accepté d\'être lié par ces Conditions d\'Utilisation et notre Politique de Confidentialité. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser nos services.',
    
    'terms.services.title': '2. Description des Services',
    'terms.services.content': 'IRONHEX fournit des solutions de cybersécurité, des services d\'intégration IoT et des services de développement logiciel aux entreprises et organisations. Nos services incluent, mais ne sont pas limités aux évaluations de sécurité, tests d\'intrusion, surveillance de la sécurité, gestion des appareils IoT et développement de logiciels personnalisés.',
    
    'terms.responsibilities.title': '3. Responsabilités de l\'Utilisateur',
    'terms.responsibilities.intro': 'En utilisant nos services, vous acceptez de :',
    'terms.responsibilities.1': 'Fournir des informations exactes et complètes',
    'terms.responsibilities.2': 'Maintenir la confidentialité de vos identifiants de compte',
    'terms.responsibilities.3': 'Utiliser nos services uniquement à des fins légales',
    'terms.responsibilities.4': 'Ne pas interférer avec ou perturber nos services',
    'terms.responsibilities.5': 'Ne pas tenter d\'accès non autorisé à nos systèmes',
    'terms.responsibilities.6': 'Se conformer à toutes les lois et réglementations applicables',
    'terms.responsibilities.7': 'Nous informer immédiatement de toute faille de sécurité',
    
    'terms.ip.title': '4. Propriété Intellectuelle',
    'terms.ip.content': 'Tout le contenu, les fonctionnalités et les fonctionnalités des services IRONHEX, y compris mais sans s\'y limiter le texte, les graphiques, les logos, les logiciels et la documentation, sont la propriété exclusive d\'IRONHEX et sont protégés par les lois internationales sur le droit d\'auteur, les marques et autres droits de propriété intellectuelle.',
    
    'terms.availability.title': '5. Disponibilité du Service',
    'terms.availability.content': 'Bien que nous nous efforcions de fournir des services fiables, nous ne garantissons pas que nos services seront ininterrompus, ponctuels, sécurisés ou sans erreur. Nous nous réservons le droit de modifier, suspendre ou interrompre toute partie de nos services à tout moment sans préavis.',
    
    'terms.confidentiality.title': '6. Confidentialité',
    'terms.confidentiality.intro': 'Nous prenons au sérieux la confidentialité de vos informations et nous nous engageons à :',
    'terms.confidentiality.1': 'Protéger vos informations confidentielles avec des mesures de sécurité conformes aux normes de l\'industrie',
    'terms.confidentiality.2': 'Ne pas divulguer vos informations à des tiers sans votre consentement',
    'terms.confidentiality.3': 'Utiliser vos informations uniquement pour fournir et améliorer nos services',
    'terms.confidentiality.4': 'Maintenir des mesures de sécurité techniques et organisationnelles appropriées',
    
    'terms.liability.title': '7. Limitation de Responsabilité',
    'terms.liability.content': 'Dans toute la mesure permise par la loi, IRONHEX ne sera pas responsable des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, ou de toute perte de profits ou de revenus, qu\'ils soient encourus directement ou indirectement, ou de toute perte de données, d\'utilisation, de clientèle ou d\'autres pertes intangibles résultant de votre utilisation de nos services.',
    
    'terms.indemnification.title': '8. Indemnisation',
    'terms.indemnification.intro': 'Vous acceptez d\'indemniser, de défendre et de dégager de toute responsabilité IRONHEX et ses dirigeants, administrateurs, employés et agents contre toutes réclamations, responsabilités, dommages, pertes et dépenses découlant de ou de quelque manière que ce soit liés à :',
    'terms.indemnification.1': 'Votre accès ou utilisation de nos services',
    'terms.indemnification.2': 'Votre violation de ces Conditions d\'Utilisation',
    'terms.indemnification.3': 'Votre violation de droits de tiers',
    'terms.indemnification.4': 'Toute utilisation non autorisée de nos services',
    
    'terms.governing.title': '9. Loi Applicable',
    'terms.governing.content': 'Ces Conditions d\'Utilisation sont régies et interprétées conformément aux lois de la Tunisie. Tout litige découlant de ces conditions sera soumis à la juridiction exclusive des tribunaux de Tunisie.',
    
    'terms.payment.title': '10. Conditions de Paiement',
    'terms.payment.content': 'Les conditions de paiement de nos services seront spécifiées dans les accords de service individuels. Tous les frais sont non remboursables sauf indication contraire par écrit. Les retards de paiement peuvent entraîner une suspension du service.',
    
    'terms.termination.title': '11. Résiliation',
    'terms.termination.content': 'Nous nous réservons le droit de résilier ou de suspendre votre accès à nos services à tout moment, sans préavis, pour une conduite que nous estimons violer ces Conditions d\'Utilisation ou nuire à d\'autres utilisateurs, à nous ou à des tiers, ou pour toute autre raison.',
    
    'terms.changes.title': '12. Modifications des Conditions',
    'terms.changes.content': 'Nous nous réservons le droit de modifier ces Conditions d\'Utilisation à tout moment. Nous informerons les utilisateurs de tout changement important en publiant les nouvelles conditions sur notre site Web. Votre utilisation continue de nos services après de tels changements constitue l\'acceptation des nouvelles conditions.',
    
    'terms.contact.title': '13. Informations de Contact',
    'terms.contact.content': 'Si vous avez des questions concernant ces Conditions d\'Utilisation, veuillez nous contacter à :',
    'terms.contact.email': 'Email : contact@ironhex-tech.com',
    'terms.contact.phone': 'Téléphone : +216 70 123 456',
    'terms.contact.address': 'Adresse : Mégrine, Tunisie',

    // Privacy Policy
    'privacy.title': 'Politique de Confidentialité',
    'privacy.lastUpdated': 'Dernière mise à jour : 31 octobre 2025',
    'privacy.intro': 'Chez IRONHEX, nous nous engageons à protéger votre vie privée et à assurer la sécurité de vos informations personnelles. Cette Politique de Confidentialité explique comment nous collectons, utilisons, divulguons et protégeons vos informations.',
    
    'privacy.collection.title': '1. Informations que Nous Collectons',
    'privacy.collection.personal.title': 'Informations Personnelles',
    'privacy.collection.personal.content': 'Nous collectons les informations que vous nous fournissez directement, notamment le nom, l\'adresse e-mail, le numéro de téléphone, le nom de l\'entreprise, le titre du poste et toute autre information que vous choisissez de fournir lorsque vous nous contactez ou utilisez nos services.',
    'privacy.collection.automatic.title': 'Informations Collectées Automatiquement',
    'privacy.collection.automatic.content': 'Lorsque vous visitez notre site Web, nous collectons automatiquement certaines informations sur votre appareil, notamment l\'adresse IP, le type de navigateur, le système d\'exploitation, les URL de référence et les pages visitées.',
    'privacy.collection.technical.title': 'Informations Techniques',
    'privacy.collection.technical.content': 'Lors de la prestation de services, nous pouvons collecter des informations techniques nécessaires pour fournir des services de cybersécurité et d\'IoT, notamment les configurations réseau, les informations sur les appareils et les journaux de sécurité.',
    
    'privacy.usage.title': '2. Comment Nous Utilisons Vos Informations',
    'privacy.usage.intro': 'Nous utilisons les informations que nous collectons pour :',
    'privacy.usage.1': 'Fournir, maintenir et améliorer nos services',
    'privacy.usage.2': 'Répondre à vos demandes et fournir un support client',
    'privacy.usage.3': 'Vous envoyer des avis techniques et des alertes de sécurité',
    'privacy.usage.4': 'Communiquer sur les produits, services et événements',
    'privacy.usage.5': 'Analyser les modèles d\'utilisation et améliorer l\'expérience utilisateur',
    'privacy.usage.6': 'Détecter, prévenir et résoudre les problèmes de sécurité',
    'privacy.usage.7': 'Se conformer aux obligations légales',
    
    'privacy.sharing.title': '3. Partage d\'Informations',
    'privacy.sharing.intro': 'Nous ne vendons pas vos informations personnelles. Nous pouvons partager vos informations uniquement dans les circonstances suivantes :',
    'privacy.sharing.1': 'Avec votre consentement explicite',
    'privacy.sharing.2': 'Avec des prestataires de services qui nous aident dans nos opérations',
    'privacy.sharing.3': 'Pour se conformer aux obligations légales',
    'privacy.sharing.4': 'Pour protéger nos droits et notre sécurité',
    'privacy.sharing.5': 'Dans le cadre d\'un transfert ou d\'une acquisition d\'entreprise',
    
    'privacy.security.title': '4. Sécurité des Données',
    'privacy.security.intro': 'Nous mettons en œuvre des mesures techniques et organisationnelles appropriées pour protéger vos informations :',
    'privacy.security.1': 'Chiffrement des données en transit et au repos',
    'privacy.security.2': 'Évaluations et audits de sécurité réguliers',
    'privacy.security.3': 'Contrôles d\'accès et mécanismes d\'authentification',
    'privacy.security.4': 'Formation des employés à la protection des données',
    'privacy.security.5': 'Procédures de réponse aux incidents',
    'privacy.security.6': 'Sauvegardes régulières et plans de reprise après sinistre',
    
    'privacy.retention.title': '5. Conservation des Données',
    'privacy.retention.content': 'Nous conservons vos informations personnelles aussi longtemps que nécessaire pour remplir les objectifs décrits dans cette Politique de Confidentialité, sauf si une période de conservation plus longue est requise ou permise par la loi. Lorsque nous n\'avons plus besoin de vos informations, nous les supprimons ou les anonymisons en toute sécurité.',
    
    'privacy.rights.title': '6. Vos Droits',
    'privacy.rights.intro': 'Vous disposez des droits suivants concernant vos informations personnelles :',
    'privacy.rights.1': 'Accès : Demander l\'accès à vos informations personnelles',
    'privacy.rights.2': 'Correction : Demander la correction d\'informations inexactes',
    'privacy.rights.3': 'Suppression : Demander la suppression de vos informations',
    'privacy.rights.4': 'Portabilité : Demander une copie de vos données dans un format portable',
    'privacy.rights.5': 'Restriction : Demander la restriction du traitement',
    'privacy.rights.6': 'Objection : Vous opposer au traitement de vos informations',
    'privacy.rights.7': 'Retrait du Consentement : Retirer votre consentement à tout moment',
    'privacy.rights.8': 'Désinscription : Vous désinscrire des communications marketing',
    
    'privacy.cookies.title': '7. Cookies et Suivi',
    'privacy.cookies.content': 'Nous utilisons des cookies et des technologies de suivi similaires pour collecter des informations sur vos activités de navigation. Vous pouvez contrôler les cookies via les paramètres de votre navigateur. Notez que la désactivation des cookies peut affecter la fonctionnalité de notre site Web.',
    
    'privacy.thirdparty.title': '8. Liens Tiers',
    'privacy.thirdparty.content': 'Notre site Web peut contenir des liens vers des sites Web tiers. Nous ne sommes pas responsables des pratiques de confidentialité de ces sites Web. Nous vous encourageons à lire leurs politiques de confidentialité.',
    
    'privacy.children.title': '9. Confidentialité des Enfants',
    'privacy.children.content': 'Nos services ne s\'adressent pas aux personnes de moins de 18 ans. Nous ne collectons pas sciemment d\'informations personnelles auprès d\'enfants. Si nous apprenons que nous avons collecté des informations auprès d\'un enfant, nous les supprimerons rapidement.',
    
    'privacy.international.title': '10. Transferts Internationaux de Données',
    'privacy.international.content': 'Vos informations peuvent être transférées et traitées dans des pays autres que votre pays de résidence. Nous veillons à ce que des garanties appropriées soient en place pour protéger vos informations conformément à cette Politique de Confidentialité.',
    
    'privacy.gdpr.title': '11. Conformité au RGPD',
    'privacy.gdpr.content': 'Pour les utilisateurs de l\'Espace Économique Européen (EEE), nous nous conformons au Règlement Général sur la Protection des Données (RGPD). Nous traitons vos données personnelles sur la base de motifs juridiques incluant le consentement, l\'exécution du contrat, les obligations légales et les intérêts légitimes.',
    
    'privacy.changes.title': '12. Modifications de la Politique de Confidentialité',
    'privacy.changes.content': 'Nous pouvons mettre à jour cette Politique de Confidentialité de temps à autre. Nous vous informerons de tout changement important en publiant la nouvelle politique sur notre site Web et en mettant à jour la date de "Dernière mise à jour". Votre utilisation continue de nos services après les modifications constitue l\'acceptation de la politique mise à jour.',
    
    'privacy.contact.title': '13. Nous Contacter',
    'privacy.contact.content': 'Si vous avez des questions concernant cette Politique de Confidentialité ou nos pratiques en matière de confidentialité, veuillez nous contacter à :',
    'privacy.contact.dpo': 'Délégué à la Protection des Données',
    'privacy.contact.email': 'Email : contact@ironhex-tech.com',
    'privacy.contact.phone': 'Téléphone : +216 70 123 456',
    'privacy.contact.address': 'Adresse : Mégrine, Tunisie',
  },
  ar: {
    // Navbar
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.cybersecurity': 'الأمن السيبراني',
    'nav.iot': 'حلول إنترنت الأشياء',
    'nav.software': 'الحلول البرمجية',
    'nav.contact': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.regulations': 'اللوائح التونسية',
    'nav.terms': 'شروط الخدمة',
    'nav.privacy': 'سياسة الخصوصية',
    
    // Footer
    'footer.company': 'IRONHEX',
    'footer.description': 'توفير حلول قوية للأمن السيبراني وحلول مبتكرة لإنترنت الأشياء لتأمين مستقبلك الرقمي.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.ourServices': 'خدماتنا',
    'footer.getInTouch': 'تواصل معنا',
    'footer.email': 'البريد الإلكتروني',
    'footer.phone': 'الهاتف',
    'footer.address': 'العنوان',
    'footer.location': 'المقرن، بن عروس',
    'footer.country': 'تونس',
    'footer.contactUs': 'اتصل بنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    
    // Home
    'home.hero.title': 'أمان لا يقهر لعالم متصل',
    'home.hero.description': 'حماية عملك بأمن سيبراني متقدم وحلول إنترنت الأشياء الذكية',
    'home.hero.cta': 'احصل على تقييم أمني مجاني',
    'home.services.title': 'خدماتنا الأساسية',
    'home.services.cyber.title': 'خدمات الأمن السيبراني',
    'home.services.cyber.desc': 'دفاع استباقي ضد التهديدات الرقمية المتطورة',
    'home.services.iot.title': 'خدمات إنترنت الأشياء',
    'home.services.iot.desc': 'تكامل آمن وسلس للأجهزة الذكية',
    'home.services.managed.title': 'الأمن المُدار والدعم',
    'home.services.managed.desc': 'مراقبة على مدار الساعة، استجابة سريعة، وإرشادات متخصصة',
    'home.testimonials.title': 'ماذا يقول العملاء',
    'home.testimonials.1': '"قامت IRONHEX بتأمين طرحنا لإنترنت الأشياء وتحسين المراقبة - فريقهم من الدرجة الأولى."',
    'home.testimonials.1.author': '- المدير التقني، Acme Corp',
    'home.testimonials.2': '"أوقات الاستجابة والخبرة استثنائية. موصى به."',
    'home.testimonials.2.author': '- رئيس قسم تكنولوجيا المعلومات، Beta Ltd',
    'home.partners.title': 'شركاؤنا',
    
    // Contact Form
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال',
    'contact.sending': 'جاري الإرسال...',
    
    // Software Solutions
    'software.title': 'حلول مواقع جاهزة',
    'software.subtitle': 'منصات ويب احترافية وكاملة الوظائف جاهزة للنشر. اطلب عرضاً توضيحياً مباشراً.',
    'software.features': 'الميزات الرئيسية:',
    'software.technologies': 'التقنيات:',
    'software.requestDemo': 'طلب عرض توضيحي',
    'software.customTitle': 'هل تحتاج إلى حل ويب مخصص؟',
    'software.customDesc': 'يمكن لفريقنا تطوير منصة ويب مخصصة مصممة خصيصاً لاحتياجات عملك الفريدة',
    'software.customCta': 'اتصل بنا للتطوير المخصص',
    
    // Demo Request
    'demo.title': 'طلب عرض توضيحي',
    'demo.description': 'املأ بياناتك وسنقوم بجدولة جلسة عرض توضيحي شخصية.',
    'demo.fullName': 'الاسم الكامل',
    'demo.email': 'عنوان البريد الإلكتروني',
    'demo.phone': 'رقم الهاتف',
    'demo.company': 'اسم الشركة (اختياري)',
    'demo.message': 'معلومات إضافية (اختياري)',
    'demo.messagePlaceholder': 'أخبرنا عن متطلباتك أو الميزات المحددة التي تهمك...',
    'demo.selectedPlatform': 'المنصة المختارة:',
    'demo.cancel': 'إلغاء',
    'demo.submit': 'إرسال الطلب',
    'demo.success': 'تم إرسال طلب العرض التوضيحي!',
    'demo.successDesc': 'سيتصل بك فريقنا خلال 24 ساعة لجدولة العرض التوضيحي.',
    'demo.error': 'خطأ',
    'demo.errorDesc': 'فشل إرسال طلب العرض التوضيحي. يرجى المحاولة مرة أخرى.',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.readMore': 'اقرأ المزيد',
    'common.learnMore': 'اعرف المزيد',
    'common.getStarted': 'ابدأ الآن',
    'common.contactUs': 'اتصل بنا',
    
    // Services Page
    'services.title': 'خدماتنا',
    'services.subtitle': 'نحن متخصصون في حلول الأمن السيبراني وإنترنت الأشياء المصممة خصيصًا لتلبية احتياجاتك. اختر مجال خدمة أدناه لمعرفة المزيد.',
    'services.cyber.title': 'خدمات الأمن السيبراني',
    'services.cyber.desc': 'دفاعات استباقية، أمان مُدار، وإرشادات الامتثال.',
    'services.cyber.cta': 'استكشف الأمن السيبراني',
    'services.iot.title': 'خدمات إنترنت الأشياء',
    'services.iot.desc': 'تكامل آمن للأجهزة، الحوسبة الطرفية، والتحليلات.',
    'services.iot.cta': 'استكشف إنترنت الأشياء',
    
    // About Page
    'about.title': 'حول IRONHEX',
    'about.subtitle': 'تأمين الغد، اليوم',
    'about.intro': 'تأسست على الخبرة، مدفوعة بالابتكار، وملتزمة بمستقبل رقمي آمن.',
    'about.story.title': 'قصتنا: وُلدت من الرؤية والخبرة',
    'about.story.p1': 'تأسست IRONHEX في تونس عام 2025 على يد مهندستين صاحبتي رؤية، كل منهما تجلب مجموعة مهارات فريدة وقوية إلى المجالات الناشئة للأمن السيبراني وإنترنت الأشياء (IoT). شغفهما المشترك بالابتكار والتزامهما الثابت بالأمن الرقمي وضع الأساس لشركة مصممة لحماية وتمكين الشركات في عالم متصل بشكل متزايد.',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'تقديم حلول أمن سيبراني متطورة وحلول إنترنت الأشياء الذكية التي تمكن الشركات من الازدهار بأمان في مشهد رقمي معقد، وتعزيز الابتكار مع ضمان سلامة البيانات والخصوصية.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.desc': 'أن نكون الشريك الموثوق الرائد في الأمن الرقمي وابتكار إنترنت الأشياء في تونس وخارجها، وتشكيل مستقبل تكون فيه التكنولوجيا قوية وآمنة بطبيعتها للجميع.',
    'about.founders.title': 'تعرف على مؤسساتنا',
    'about.founder1.name': 'إيمان الشيحي',
    'about.founder1.role': 'مؤسس مشارك ومدير أمن المعلومات',
    'about.founder1.desc': 'عقل متألق في الأمن السيبراني، تقود إيمان استراتيجيات الدفاع في IRONHEX، وتضمن حماية عملائنا وأصولهم من أكثر التهديدات الرقمية تطورًا. تمتد خبرتها عبر استخبارات التهديدات والاستجابة للحوادث وتصميم البنية المعمارية الآمنة.',
    'about.founder2.name': 'أريج صالح',
    'about.founder2.role': 'مؤسس مشارك ومدير التكنولوجيا',
    'about.founder2.desc': 'أريج هي القوة الدافعة وراء حلول إنترنت الأشياء المبتكرة في IRONHEX. مع فهم عميق للنظم البيئية المتصلة، تقوم بتصميم عمليات نشر إنترنت الأشياء الذكية والفعالة والقابلة للتطوير التي تحول الشركات والصناعات.',
    'about.journey.title': 'انضم إلى رحلتنا',
    'about.journey.desc': 'نحن دائمًا نبحث عن مواهب متحمسة للانضمام إلى فريقنا المتنامي. استكشف فرص العمل أو تواصل معنا لمعرفة المزيد حول كيف يمكننا تأمين عالمك الرقمي.',
    'about.journey.cta': 'اتصل بنا',
    
    // Cybersecurity Page
    'cyber.hero.title': 'حصّن قلعتك الرقمية',
    'cyber.hero.desc': 'توفر IRONHEX حلول أمن سيبراني شاملة لحماية عملك من التهديدات المتطورة وضمان المرونة الرقمية.',
    'cyber.hero.offerings': 'عروضنا',
    'cyber.hero.consultation': 'احصل على استشارة',
    'cyber.intro.title': 'دفاع استباقي في مشهد رقمي معقد',
    'cyber.intro.p1': 'في عالم اليوم المترابط، الأمن السيبراني ليس مجرد ضرورة؛ إنه أساس استمرارية الأعمال والثقة. تقدم IRONHEX مجموعة كاملة من خدمات الأمن السيبراني المصممة لتحديد وحماية واكتشاف والاستجابة والتعافي من التهديدات السيبرانية.',
    'cyber.intro.p2': 'نحن نجمع بين التكنولوجيا المتطورة والذكاء البشري الخبير لبناء دفاعات متعددة الطبقات تحمي بياناتك وأنظمتك وسمعتك ضد الهجمات المتطورة.',
    'cyber.services.title': 'طيف خدمات الأمن السيبراني لدينا',
    'cyber.service1.title': 'خدمات الأمن المُدارة',
    'cyber.service1.desc': 'مراقبة 24/7، كشف التهديدات، واستجابة سريعة من قبل خبراء مركز العمليات الأمنية (SOC).',
    'cyber.service2.title': 'إدارة الثغرات',
    'cyber.service2.desc': 'فحص منتظم، اختبار الاختراق، وتقييمات المخاطر لتحديد وتخفيف نقاط الضعف الأمنية.',
    'cyber.service3.title': 'أمن السحابة',
    'cyber.service3.desc': 'تأمين البنية التحتية السحابية الخاصة بك (AWS، Azure، GCP)، والتطبيقات، والبيانات بضوابط قوية.',
    'cyber.service4.title': 'حماية نقاط النهاية',
    'cyber.service4.desc': 'حماية متقدمة لجميع الأجهزة، من أجهزة الكمبيوتر المحمولة إلى الخوادم، ضد البرامج الضارة وبرامج الفدية والتهديدات يوم الصفر.',
    'cyber.service5.title': 'إدارة الهوية والوصول (IAM)',
    'cyber.service5.desc': 'التحكم في من يصل إلى ماذا، وفرض المصادقة متعددة العوامل، وإدارة هويات المستخدمين بشكل آمن.',
    'cyber.service6.title': 'دعم الامتثال والتنظيم',
    'cyber.service6.desc': 'التنقل في المشاهد التنظيمية المعقدة (GDPR، HIPAA، ISO 27001) مع إرشادات وحلول خبرائنا.',
    
    // IoT Page
    'iot.hero.title': 'تكامل إنترنت الأشياء الآمن والسلس',
    'iot.hero.desc': 'أطلق العنان للإمكانات الكاملة لأجهزتك المتصلة مع حلول إنترنت الأشياء الذكية من IRONHEX، المصممة للأمان والكفاءة.',
    'iot.hero.features': 'استكشف الميزات',
    'iot.hero.consultation': 'احصل على استشارة',
    'iot.intro.title': 'حوّل عملك بإنترنت الأشياء الذكي',
    'iot.intro.p1': 'يُحدث إنترنت الأشياء (IoT) ثورة في الصناعات من خلال ربط الأجهزة المادية بالإنترنت، مما يمكنها من جمع وتبادل البيانات. في IRONHEX، نمكن عملك من تسخير هذه القوة من خلال حلول إنترنت الأشياء الآمنة والقابلة للتطوير والذكية.',
    'iot.intro.p2': 'من البنية التحتية الذكية إلى الأتمتة الصناعية، يقوم خبراؤنا بتصميم وتنفيذ وإدارة النظم البيئية لإنترنت الأشياء التي تدفع الكفاءة والابتكار والنمو مع ضمان أمان قوي من الحافة إلى السحابة.',
    'iot.services.title': 'عروض خدمات إنترنت الأشياء الشاملة لدينا',
    'iot.service1.title': 'استراتيجية واستشارات إنترنت الأشياء',
    'iot.service1.desc': 'تطوير خارطة طريق واضحة لإنترنت الأشياء تتماشى مع أهداف عملك، من اختيار الجهاز إلى تكامل المنصة.',
    'iot.service2.title': 'إدارة أجهزة إنترنت الأشياء الآمنة',
    'iot.service2.desc': 'ضمان التوفير والمراقبة والتحديث الآمن لجميع أجهزتك المتصلة طوال دورة حياتها.',
    'iot.service3.title': 'تكامل السحابة وتحليلات البيانات',
    'iot.service3.desc': 'ربط أجهزة إنترنت الأشياء الخاصة بك بسلاسة بمنصات السحابة واستخلاص رؤى قابلة للتنفيذ من البيانات المجمعة.',
    'iot.service4.title': 'أمان وامتثال إنترنت الأشياء',
    'iot.service4.desc': 'تنفيذ بروتوكولات أمان متعددة الطبقات وضمان الامتثال لمعايير الصناعة لحماية النظام البيئي لإنترنت الأشياء الخاص بك.',
    'iot.service5.title': 'حلول الحوسبة الطرفية',
    'iot.service5.desc': 'معالجة البيانات بالقرب من المصدر لاتخاذ القرارات في الوقت الفعلي، وتقليل زمن الوصول، وتعزيز الأمان.',
    'iot.service6.title': 'إنترنت الأشياء الصناعي (IIoT)',
    'iot.service6.desc': 'تحسين التصنيع وسلسلة التوريد وإدارة الأصول مع تطبيقات IIoT القوية والآمنة.',
    
    // FAQ Page
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'اعثر على إجابات للأسئلة الشائعة حول خدمات IRONHEX',
    'faq.cat.general': 'معلومات عامة',
    'faq.cat.services': 'الخدمات والدعم',
    'faq.cat.technical': 'أسئلة تقنية',
    'faq.cat.billing': 'التسعير والفواتير',
    'faq.questions': 'سؤال',
    'faq.questions_plural': 'أسئلة',
    'faq.cta.title': 'لا تزال لديك أسئلة؟',
    'faq.cta.desc': 'فريقنا هنا للمساعدة. اتصل بنا للحصول على مساعدة شخصية.',
    'faq.cta.button': 'اتصل بنا',
    
    'faq.q1': 'ما هي الخدمات التي تقدمها IRONHEX؟',
    'faq.a1': 'تتخصص IRONHEX في حلول الأمن السيبراني الشاملة وخدمات إنترنت الأشياء. نقدم اختبار الاختراق، وتدقيق الأمان، وتقييم نقاط الضعف، وإدارة أجهزة إنترنت الأشياء، وحلول البرمجيات المخصصة لعملاء المؤسسات.',
    'faq.q2': 'كيف يمكنني البدء بخدمات IRONHEX؟',
    'faq.a2': 'البدء سهل! ما عليك سوى الاتصال بنا من خلال نموذج الاتصال أو البريد الإلكتروني أو الهاتف. سيقوم فريقنا بجدولة استشارة لفهم متطلباتك واقتراح أفضل حل لاحتياجاتك.',
    'faq.q3': 'هل تقدمون الدعم على مدار الساعة طوال أيام الأسبوع؟',
    'faq.a3': 'نعم، نقدم دعمًا على مدار الساعة طوال أيام الأسبوع لعملاء المؤسسات وعملاء الخدمات المُدارة. فريق الدعم لدينا متاح دائمًا لمعالجة الحوادث الأمنية الحرجة وتقديم المساعدة التقنية.',
    'faq.q4': 'ما هي الصناعات التي تخدمونها؟',
    'faq.a4': 'نخدم مجموعة واسعة من الصناعات بما في ذلك الخدمات المالية والرعاية الصحية والتصنيع والبيع بالتجزئة والوكالات الحكومية وشركات التكنولوجيا. حلولنا مصممة خصيصًا لتلبية متطلبات الامتثال والأمان الخاصة بالصناعة.',
    'faq.q5': 'كم من الوقت يستغرق تدقيق الأمان؟',
    'faq.a5': 'تعتمد مدة تدقيق الأمان على نطاق وتعقيد بنيتك التحتية. عادةً، يستغرق التدقيق الشامل من 2 إلى 4 أسابيع. نحن نقدم جدولًا زمنيًا مفصلاً أثناء الاستشارة الأولية.',
    'faq.q6': 'ما هو اختبار الاختراق؟',
    'faq.a6': 'اختبار الاختراق هو هجوم إلكتروني محاكى على نظامك لتحديد نقاط الضعف قبل أن يتمكن الجهات الفاعلة الخبيثة من استغلالها. يستخدم قراصنة أخلاقيون معتمدون لدينا منهجيات معيارية في الصناعة لاختبار وضعك الأمني.',
    'faq.q7': 'هل تقدمون خدمات التدريب؟',
    'faq.a7': 'نعم، نقدم تدريبًا على الوعي الأمني للموظفين، وتدريبًا تقنيًا لفرق تكنولوجيا المعلومات، ودورات تحضيرية متخصصة لشهادات الأمن السيبراني.',
    'faq.q8': 'ما هو نموذج التسعير الخاص بك؟',
    'faq.a8': 'نقدم نماذج تسعير مرنة بما في ذلك المشاريع والعقود الشهرية والحزم المخصصة. يعتمد التسعير على نطاق الخدمات والمدة والمتطلبات المحددة. اتصل بنا للحصول على عرض أسعار مفصل.',
    'faq.q9': 'هل حلولكم متوافقة مع اللوائح؟',
    'faq.a9': 'نعم، تم تصميم حلولنا لمساعدتك في تلبية متطلبات الامتثال المختلفة بما في ذلك اللائحة العامة لحماية البيانات، HIPAA، PCI-DSS، ISO 27001 واللوائح المحلية. يمكننا المساعدة في تدقيق الامتثال والتوثيق.',
    'faq.q10': 'هل يمكنكم المساعدة في الاستجابة للحوادث؟',
    'faq.a10': 'بالتأكيد. نقدم خدمات استجابة سريعة للحوادث لمساعدتك في احتواء واستقصاء والتعافي من الاختراقات الأمنية. يمكن إشراك فريقنا عند الطلب أو من خلال عقد للحصول على استجابة ذات أولوية.',
    'faq.q11': 'ما الذي يميز IRONHEX عن المنافسين؟',
    'faq.a11': 'تجمع IRONHEX بين الخبرة التقنية العميقة ونهج يركز على العميل. نقدم حلولًا مخصصة، ونحافظ على الشفافية طوال المشاركات، ونضمن نقل المعرفة لتمكين فريقك.',
    'faq.q12': 'هل تقدمون خدمات عن بُعد أو في الموقع؟',
    'faq.a12': 'نقدم خدمات عن بُعد وفي الموقع حسب متطلباتك. يمكن إجراء العديد من التقييمات عن بُعد، بينما قد يتطلب البعض الآخر حضورًا في الموقع لاختبار الأمن المادي أو البيئات الحساسة.',
    
    // Tunisian Regulations Page
    'reg.title': 'اللوائح التونسية للأمن السيبراني',
    'reg.subtitle': 'فهم الإطار القانوني التونسي للأمن السيبراني وحماية البيانات',
    'reg.alert.title': 'الامتثال التنظيمي',
    'reg.alert.desc': 'تضمن IRONHEX أن جميع الخدمات متوافقة مع قوانين الأمن السيبراني التونسية والمعايير الدولية.',
    
    'reg.section1.title': 'قانون حماية البيانات',
    'reg.section1.subtitle': 'القانون الأساسي رقم 2004-63 المتعلق بحماية البيانات الشخصية',
    'reg.section1.p1': 'ينشئ قانون حماية البيانات التونسي الإطار لجمع ومعالجة وتخزين البيانات الشخصية. يجب على المؤسسات الحصول على موافقة صريحة قبل معالجة المعلومات الشخصية وتنفيذ تدابير أمنية مناسبة لحماية البيانات.',
    'reg.section1.requirements': 'المتطلبات الرئيسية:',
    'reg.section1.req1': 'التسجيل لدى الهيئة الوطنية لحماية البيانات الشخصية (INPDP)',
    'reg.section1.req2': 'تنفيذ تدابير الأمان التقنية والتنظيمية',
    'reg.section1.req3': 'الإخطار بخرق البيانات في غضون 72 ساعة',
    'reg.section1.req4': 'حقوق موضوع البيانات بما في ذلك الوصول والتصحيح والحذف',
    
    'reg.section2.title': 'قانون الجرائم السيبرانية',
    'reg.section2.subtitle': 'القانون رقم 2004-5 المتعلق بأمن الكمبيوتر وحماية البيانات',
    'reg.section2.p1': 'يعالج هذا القانون الجرائم السيبرانية ويحدد العقوبات على الوصول غير المصرح به إلى أنظمة الكمبيوتر وسرقة البيانات والجرائم السيبرانية الأخرى. يوفر الأساس القانوني لمقاضاة مجرمي الإنترنت وحماية البنية التحتية للمعلومات الحيوية.',
    'reg.section2.offenses': 'الجرائم المشمولة:',
    'reg.section2.off1': 'الوصول غير المصرح به إلى أنظمة الكمبيوتر',
    'reg.section2.off2': 'سرقة البيانات والاحتيال',
    'reg.section2.off3': 'توزيع البرامج الضارة',
    'reg.section2.off4': 'التحرش السيبراني والتهديدات عبر الإنترنت',
    
    'reg.section3.title': 'تنظيم الاتصالات الإلكترونية',
    'reg.section3.subtitle': 'قانون الاتصالات ولوائح الهيئة الوطنية للاتصالات',
    'reg.section3.p1': 'تنظم الهيئة الوطنية للاتصالات في تونس (INTT) الاتصالات الإلكترونية وأمن الشبكات. يجب على مقدمي الخدمات الامتثال للمعايير التقنية ومتطلبات الأمان.',
    
    'reg.section4.title': 'كيف تضمن IRONHEX الامتثال',
    'reg.section4.p1': 'تعمل IRONHEX مع المؤسسات لضمان الامتثال الكامل للوائح الأمن السيبراني التونسية:',
    'reg.section4.service1.title': 'تدقيق الامتثال',
    'reg.section4.service1.desc': 'تقييمات شاملة لحالة الامتثال الحالية الخاصة بك مقابل اللوائح التونسية',
    'reg.section4.service2.title': 'تطوير السياسات',
    'reg.section4.service2.desc': 'إنشاء سياسات وإجراءات متوافقة مع المتطلبات القانونية',
    'reg.section4.service3.title': 'تنفيذ الأمان',
    'reg.section4.service3.desc': 'نشر الضوابط التقنية لتلبية معايير الأمان التنظيمية',
    'reg.section4.service4.title': 'المراقبة المستمرة',
    'reg.section4.service4.desc': 'مراقبة وإبلاغ الامتثال المستمر',
    
    'reg.disclaimer.title': 'إخلاء المسؤولية:',
    'reg.disclaimer.text': 'يتم توفير هذه المعلومات للإرشاد العام فقط ولا تشكل نصيحة قانونية. للأسئلة القانونية المحددة، يرجى استشارة محامٍ مؤهل.',
    
    'reg.cta.title': 'تحتاج مساعدة في الامتثال؟',
    'reg.cta.desc': 'اتصل بخبرائنا لضمان امتثال مؤسستك لجميع المتطلبات التنظيمية',
    'reg.cta.button': 'ابدأ الآن',

    // Terms of Service
    'terms.title': 'شروط الخدمة',
    'terms.lastUpdated': 'آخر تحديث: 31 أكتوبر 2025',
    'terms.intro': 'مرحباً بك في IRONHEX. من خلال الوصول إلى خدماتنا أو استخدامها، فإنك توافق على الالتزام بشروط الخدمة هذه. يرجى قراءتها بعناية.',
    
    'terms.acceptance.title': '1. قبول الشروط',
    'terms.acceptance.content': 'من خلال الوصول إلى خدمات IRONHEX واستخدامها، فإنك تقر بأنك قد قرأت وفهمت ووافقت على الالتزام بشروط الخدمة هذه وسياسة الخصوصية الخاصة بنا. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام خدماتنا.',
    
    'terms.services.title': '2. وصف الخدمات',
    'terms.services.content': 'تقدم IRONHEX حلول الأمن السيبراني، وخدمات تكامل إنترنت الأشياء، وخدمات تطوير البرمجيات للشركات والمؤسسات. تشمل خدماتنا على سبيل المثال لا الحصر تقييمات الأمن، واختبار الاختراق، ومراقبة الأمن، وإدارة أجهزة إنترنت الأشياء، وتطوير البرمجيات المخصصة.',
    
    'terms.responsibilities.title': '3. مسؤوليات المستخدم',
    'terms.responsibilities.intro': 'عند استخدام خدماتنا، فإنك توافق على:',
    'terms.responsibilities.1': 'تقديم معلومات دقيقة وكاملة',
    'terms.responsibilities.2': 'الحفاظ على سرية بيانات اعتماد حسابك',
    'terms.responsibilities.3': 'استخدام خدماتنا فقط للأغراض القانونية',
    'terms.responsibilities.4': 'عدم التدخل في خدماتنا أو تعطيلها',
    'terms.responsibilities.5': 'عدم محاولة الوصول غير المصرح به إلى أنظمتنا',
    'terms.responsibilities.6': 'الامتثال لجميع القوانين واللوائح المعمول بها',
    'terms.responsibilities.7': 'إخطارنا فوراً بأي خروقات أمنية',
    
    'terms.ip.title': '4. الملكية الفكرية',
    'terms.ip.content': 'جميع المحتويات والميزات والوظائف الخاصة بخدمات IRONHEX، بما في ذلك على سبيل المثال لا الحصر النصوص والرسومات والشعارات والبرامج والوثائق، هي ملكية حصرية لـ IRONHEX ومحمية بموجب قوانين حقوق النشر والعلامات التجارية وغيرها من قوانين الملكية الفكرية الدولية.',
    
    'terms.availability.title': '5. توفر الخدمة',
    'terms.availability.content': 'بينما نسعى جاهدين لتقديم خدمات موثوقة، فإننا لا نضمن أن خدماتنا ستكون متواصلة أو في الوقت المناسب أو آمنة أو خالية من الأخطاء. نحتفظ بالحق في تعديل أو تعليق أو إيقاف أي جزء من خدماتنا في أي وقت دون إشعار.',
    
    'terms.confidentiality.title': '6. السرية',
    'terms.confidentiality.intro': 'نحن نأخذ سرية معلوماتك على محمل الجد ونلتزم بـ:',
    'terms.confidentiality.1': 'حماية معلوماتك السرية بتدابير أمنية متوافقة مع معايير الصناعة',
    'terms.confidentiality.2': 'عدم الكشف عن معلوماتك لأطراف ثالثة دون موافقتك',
    'terms.confidentiality.3': 'استخدام معلوماتك فقط لتقديم خدماتنا وتحسينها',
    'terms.confidentiality.4': 'الحفاظ على تدابير أمنية تقنية وتنظيمية مناسبة',
    
    'terms.liability.title': '7. حدود المسؤولية',
    'terms.liability.content': 'إلى أقصى حد يسمح به القانون، لن تكون IRONHEX مسؤولة عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية، أو أي خسارة في الأرباح أو الإيرادات، سواء تم تكبدها بشكل مباشر أو غير مباشر، أو أي خسارة للبيانات أو الاستخدام أو السمعة أو غيرها من الخسائر غير الملموسة الناتجة عن استخدامك لخدماتنا.',
    
    'terms.indemnification.title': '8. التعويض',
    'terms.indemnification.intro': 'أنت توافق على تعويض والدفاع عن IRONHEX ومسؤوليها ومديريها وموظفيها ووكلائها وحمايتهم من أي مطالبات ومسؤوليات وأضرار وخسائر ونفقات ناشئة عن أو متصلة بأي شكل من الأشكال بـ:',
    'terms.indemnification.1': 'وصولك إلى خدماتنا أو استخدامها',
    'terms.indemnification.2': 'انتهاكك لشروط الخدمة هذه',
    'terms.indemnification.3': 'انتهاكك لحقوق أي طرف ثالث',
    'terms.indemnification.4': 'أي استخدام غير مصرح به لخدماتنا',
    
    'terms.governing.title': '9. القانون الحاكم',
    'terms.governing.content': 'تخضع شروط الخدمة هذه وتفسر وفقاً لقوانين تونس. أي نزاعات ناشئة عن هذه الشروط تخضع للاختصاص الحصري لمحاكم تونس.',
    
    'terms.payment.title': '10. شروط الدفع',
    'terms.payment.content': 'سيتم تحديد شروط الدفع لخدماتنا في اتفاقيات الخدمة الفردية. جميع الرسوم غير قابلة للاسترداد ما لم ينص على خلاف ذلك كتابياً. قد تؤدي التأخيرات في الدفع إلى تعليق الخدمة.',
    
    'terms.termination.title': '11. الإنهاء',
    'terms.termination.content': 'نحتفظ بالحق في إنهاء أو تعليق وصولك إلى خدماتنا في أي وقت، دون إشعار مسبق، لسلوك نعتقد أنه يخالف شروط الخدمة هذه أو يضر بمستخدمين آخرين أو بنا أو بأطراف ثالثة، أو لأي سبب آخر.',
    
    'terms.changes.title': '12. التغييرات على الشروط',
    'terms.changes.content': 'نحتفظ بالحق في تعديل شروط الخدمة هذه في أي وقت. سنخطر المستخدمين بأي تغييرات جوهرية من خلال نشر الشروط الجديدة على موقعنا الإلكتروني. استمرارك في استخدام خدماتنا بعد هذه التغييرات يشكل قبولاً للشروط الجديدة.',
    
    'terms.contact.title': '13. معلومات الاتصال',
    'terms.contact.content': 'إذا كان لديك أي أسئلة حول شروط الخدمة هذه، يرجى الاتصال بنا على:',
    'terms.contact.email': 'البريد الإلكتروني: contact@ironhex-tech.com',
    'terms.contact.phone': 'الهاتف: 456 123 70 216+',
    'terms.contact.address': 'العنوان: مقرين، تونس',

    // Privacy Policy
    'privacy.title': 'سياسة الخصوصية',
    'privacy.lastUpdated': 'آخر تحديث: 31 أكتوبر 2025',
    'privacy.intro': 'في IRONHEX، نحن ملتزمون بحماية خصوصيتك وضمان أمان معلوماتك الشخصية. توضح سياسة الخصوصية هذه كيفية جمع معلوماتك واستخدامها والكشف عنها وحمايتها.',
    
    'privacy.collection.title': '1. المعلومات التي نجمعها',
    'privacy.collection.personal.title': 'المعلومات الشخصية',
    'privacy.collection.personal.content': 'نجمع المعلومات التي تقدمها لنا مباشرة، بما في ذلك الاسم وعنوان البريد الإلكتروني ورقم الهاتف واسم الشركة والمسمى الوظيفي وأي معلومات أخرى تختار تقديمها عند الاتصال بنا أو استخدام خدماتنا.',
    'privacy.collection.automatic.title': 'المعلومات المجمعة تلقائياً',
    'privacy.collection.automatic.content': 'عند زيارة موقعنا الإلكتروني، نجمع تلقائياً معلومات معينة عن جهازك، بما في ذلك عنوان IP ونوع المتصفح ونظام التشغيل وعناوين URL المرجعية والصفحات التي تمت زيارتها.',
    'privacy.collection.technical.title': 'المعلومات التقنية',
    'privacy.collection.technical.content': 'أثناء تقديم الخدمة، قد نجمع معلومات تقنية ضرورية لتقديم خدمات الأمن السيبراني وإنترنت الأشياء، بما في ذلك تكوينات الشبكة ومعلومات الجهاز وسجلات الأمان.',
    
    'privacy.usage.title': '2. كيف نستخدم معلوماتك',
    'privacy.usage.intro': 'نستخدم المعلومات التي نجمعها من أجل:',
    'privacy.usage.1': 'توفير خدماتنا والحفاظ عليها وتحسينها',
    'privacy.usage.2': 'الرد على استفساراتك وتقديم دعم العملاء',
    'privacy.usage.3': 'إرسال إشعارات فنية وتنبيهات أمنية',
    'privacy.usage.4': 'التواصل بشأن المنتجات والخدمات والفعاليات',
    'privacy.usage.5': 'تحليل أنماط الاستخدام وتحسين تجربة المستخدم',
    'privacy.usage.6': 'اكتشاف المشكلات الأمنية ومنعها ومعالجتها',
    'privacy.usage.7': 'الامتثال للالتزامات القانونية',
    
    'privacy.sharing.title': '3. مشاركة المعلومات',
    'privacy.sharing.intro': 'نحن لا نبيع معلوماتك الشخصية. قد نشارك معلوماتك فقط في الظروف التالية:',
    'privacy.sharing.1': 'بموافقتك الصريحة',
    'privacy.sharing.2': 'مع مقدمي الخدمات الذين يساعدوننا في عملياتنا',
    'privacy.sharing.3': 'للامتثال للالتزامات القانونية',
    'privacy.sharing.4': 'لحماية حقوقنا وسلامتنا',
    'privacy.sharing.5': 'فيما يتعلق بنقل الأعمال أو الاستحواذ',
    
    'privacy.security.title': '4. أمن البيانات',
    'privacy.security.intro': 'نطبق تدابير تقنية وتنظيمية مناسبة لحماية معلوماتك:',
    'privacy.security.1': 'تشفير البيانات أثناء النقل وأثناء الراحة',
    'privacy.security.2': 'تقييمات وعمليات تدقيق أمنية منتظمة',
    'privacy.security.3': 'ضوابط الوصول وآليات المصادقة',
    'privacy.security.4': 'تدريب الموظفين على حماية البيانات',
    'privacy.security.5': 'إجراءات الاستجابة للحوادث',
    'privacy.security.6': 'نسخ احتياطية منتظمة وخطط التعافي من الكوارث',
    
    'privacy.retention.title': '5. الاحتفاظ بالبيانات',
    'privacy.retention.content': 'نحتفظ بمعلوماتك الشخصية طالما كان ذلك ضرورياً لتحقيق الأغراض الموضحة في سياسة الخصوصية هذه، ما لم يكن القانون يتطلب أو يسمح بفترة احتفاظ أطول. عندما لا نعود بحاجة إلى معلوماتك، نقوم بحذفها أو إخفاء هويتها بشكل آمن.',
    
    'privacy.rights.title': '6. حقوقك',
    'privacy.rights.intro': 'لديك الحقوق التالية فيما يتعلق بمعلوماتك الشخصية:',
    'privacy.rights.1': 'الوصول: طلب الوصول إلى معلوماتك الشخصية',
    'privacy.rights.2': 'التصحيح: طلب تصحيح المعلومات غير الدقيقة',
    'privacy.rights.3': 'الحذف: طلب حذف معلوماتك',
    'privacy.rights.4': 'النقل: طلب نسخة من بياناتك بتنسيق قابل للنقل',
    'privacy.rights.5': 'التقييد: طلب تقييد المعالجة',
    'privacy.rights.6': 'الاعتراض: الاعتراض على معالجة معلوماتك',
    'privacy.rights.7': 'سحب الموافقة: سحب موافقتك في أي وقت',
    'privacy.rights.8': 'إلغاء الاشتراك: إلغاء الاشتراك في الاتصالات التسويقية',
    
    'privacy.cookies.title': '7. ملفات تعريف الارتباط والتتبع',
    'privacy.cookies.content': 'نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة لجمع معلومات حول أنشطة التصفح الخاصة بك. يمكنك التحكم في ملفات تعريف الارتباط من خلال إعدادات المتصفح. لاحظ أن تعطيل ملفات تعريف الارتباط قد يؤثر على وظائف موقعنا الإلكتروني.',
    
    'privacy.thirdparty.title': '8. روابط الأطراف الثالثة',
    'privacy.thirdparty.content': 'قد يحتوي موقعنا الإلكتروني على روابط لمواقع أطراف ثالثة. نحن لسنا مسؤولين عن ممارسات الخصوصية لهذه المواقع. نشجعك على قراءة سياسات الخصوصية الخاصة بهم.',
    
    'privacy.children.title': '9. خصوصية الأطفال',
    'privacy.children.content': 'خدماتنا غير موجهة للأفراد الذين تقل أعمارهم عن 18 عاماً. نحن لا نجمع عن قصد معلومات شخصية من الأطفال. إذا علمنا أننا قد جمعنا معلومات من طفل، فسنحذفها على الفور.',
    
    'privacy.international.title': '10. النقل الدولي للبيانات',
    'privacy.international.content': 'قد يتم نقل معلوماتك ومعالجتها في دول غير بلد إقامتك. نضمن وجود ضمانات مناسبة لحماية معلوماتك وفقاً لسياسة الخصوصية هذه.',
    
    'privacy.gdpr.title': '11. الامتثال للائحة حماية البيانات العامة',
    'privacy.gdpr.content': 'بالنسبة للمستخدمين في المنطقة الاقتصادية الأوروبية (EEA)، نحن نلتزم باللائحة العامة لحماية البيانات (GDPR). نعالج بياناتك الشخصية بناءً على أسس قانونية تشمل الموافقة وتنفيذ العقد والالتزامات القانونية والمصالح المشروعة.',
    
    'privacy.changes.title': '12. التغييرات على سياسة الخصوصية',
    'privacy.changes.content': 'قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سنخطرك بأي تغييرات جوهرية من خلال نشر السياسة الجديدة على موقعنا الإلكتروني وتحديث تاريخ "آخر تحديث". استمرارك في استخدام خدماتنا بعد التغييرات يشكل قبولاً للسياسة المحدثة.',
    
    'privacy.contact.title': '13. اتصل بنا',
    'privacy.contact.content': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه أو ممارسات الخصوصية لدينا، يرجى الاتصال بنا على:',
    'privacy.contact.dpo': 'مسؤول حماية البيانات',
    'privacy.contact.email': 'البريد الإلكتروني: contact@ironhex-tech.com',
    'privacy.contact.phone': 'الهاتف: 456 123 70 216+',
    'privacy.contact.address': 'العنوان: مقرين، تونس',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
